#include <mrs/desktop.hpp>
#include <mrs/vst3.hpp>
#include <mrs/ahead_renderer.hpp>
#include <cstdlib>
#include <iostream>
#include <new>
#include <cmath>
namespace {
using namespace mrs;using namespace mrs::audio;using namespace mrs::processing;using namespace mrs::desktop;
thread_local bool probe{};std::atomic<unsigned> allocations{};
void check(bool b,const char* s){if(!b)throw std::runtime_error(s);}
#define CHECK(...) check(static_cast<bool>((__VA_ARGS__)),#__VA_ARGS__)
template<class F>void rejects(F f){bool caught=false;try{f();}catch(const std::exception&){caught=true;}CHECK(caught);}
struct Directory{std::filesystem::path path=std::filesystem::temp_directory_path()/("mrs-midi-clips-"+new_id().value);Directory(){std::filesystem::create_directory(path);}~Directory(){std::error_code e;std::filesystem::remove_all(path,e);}};
struct ManualDevice final:IAudioDevice{
    DevicePhase phase{DevicePhase::closed};std::vector<DeviceInfo> enumerate()override{return {{0,"MIDI clip fixture",{"Mic"}, {"L","R"},16,8192,128,1}};}
    void control_panel(int)override{}void open(const DeviceConfig&,std::shared_ptr<AudioEngine>)override{phase=DevicePhase::open;}void start()override{phase=DevicePhase::running;}void stop()override{phase=DevicePhase::stopped;}void close()noexcept override{phase=DevicePhase::closed;}DeviceStatus status()override{return {phase,48000};}
};
struct Synth final:IProcessor{
    std::array<float,2048> held{};
    std::vector<ParameterInfo> parameters()const override{return {};}
    void prepare(ProcessConfig)override{}void restore(const PluginState&)override{}PluginState capture()const override{return {};}
    bool set_parameter(std::uint32_t,float)noexcept override{return false;}std::optional<float> parameter_value(std::uint32_t)const noexcept override{return {};}
    std::uint32_t latency()const noexcept override{return 0;}bool live_safe()const noexcept override{return true;}void warm()override{}void reset()noexcept override{held.fill(0);}
    void process(ProcessBlock b)noexcept override{for(std::uint32_t f=0;f<b.frames;++f){for(const auto& e:b.midi)if(e.offset==f){auto& n=held[e.channel*128+e.data1];if(e.kind==MidiKind::note_on)n=e.data2/127.f*.25f;else if(e.kind==MidiKind::note_off)n=0;else if(e.kind==MidiKind::cc&&(e.data1==120||e.data1==123))for(int pitch=0;pitch<128;++pitch)held[e.channel*128+pitch]=0;}float sum=0;for(const auto n:held)sum+=n;for(std::uint32_t c=0;c<b.channels;++c)b.audio[f*b.channels+c]=sum;}}
};
std::shared_ptr<PreparedGraph> synth(std::uint32_t rate=48000){GraphState g;g.id=new_id();NodeState n;n.id=new_id();n.processor_id="timeline-synth";g.nodes={n};g.outputs={n.id};return std::make_shared<PreparedGraph>(GraphSnapshot{std::make_shared<const GraphState>(g),0,false,false},ProcessConfig{rate,2,128,128,true},[](const NodeState&){return std::make_unique<Synth>();});}
Project project(){Project p;p.id=new_id();p.title="MIDI test";Track t;t.id=new_id();t.name="Keys";t.kind=TrackKind::instrument;p.tracks={t};Clip c;c.id=new_id();c.track=t.id;c.name="Phrase";c.midi=MidiClip{0,4*ppq,0,{{new_id(),0,2*ppq,60,127,0},{new_id(),2*ppq,ppq,64,90,2}}};p.clips={c};p.validate();return p;}
void model(){auto p=project();ProjectStore s(p);auto id=p.clips.front().id,track=p.tracks.front().id;const auto note=p.clips.front().midi->notes.front().id;
    s.execute(TrimMidiClip{id,ppq,4*ppq});CHECK(s.state().project->clips.front().midi->source_offset==ppq);CHECK(s.undo());CHECK(s.redo());CHECK(s.undo());
    auto right=new_id();s.execute(SplitMidiClip{id,ppq,right});CHECK(s.state().project->clips.size()==2&&s.state().project->clips.front().midi->length==ppq);CHECK(s.state().project->clips.back().midi->notes.front().id!=note);CHECK(s.state().project->clips.back().midi->source_offset==ppq);CHECK(s.undo());
    auto duplicate=new_id();s.execute(DuplicateClip{id,duplicate});CHECK(s.state().project->clips.back().midi->start==4*ppq);CHECK(s.undo());s.execute(MoveMidiClip{id,track,8*ppq});CHECK(s.state().project->clips.front().midi->start==8*ppq);CHECK(s.undo());
    auto notes=p.clips.front().midi->notes;notes[0].pitch=72;s.execute(SetMidiNotes{id,notes});CHECK(s.state().project->clips.front().midi->notes.front().id==note);auto bytes=serialize(*s.state().project);CHECK(deserialize(bytes)==*s.state().project);CHECK(s.undo());CHECK(s.redo());
    auto rev=s.state().revision;notes[0].velocity=0;rejects([&]{s.execute(SetMidiNotes{id,notes});});CHECK(s.state().revision==rev);rejects([&]{s.execute(MoveMidiClip{id,Id{"missing"},0});});rejects([&]{s.execute(TrimMidiClip{id,-1,1});});
    s.execute(RemoveClip{id});CHECK(s.state().project->clips.empty());CHECK(s.undo());
    auto old=serialize(demo_project());const std::string line="MIDI 0\nMIDIEVENTS 0\n";for(auto at=old.find(line);at!=std::string::npos;at=old.find(line))old.erase(at,line.size());old.replace(0,std::string("MRS_CORE_SNAPSHOT 13").size(),"MRS_CORE_SNAPSHOT 11");CHECK(deserialize(old)==demo_project());
    p.time.tempos={{0,120},{ppq,60}};auto compiled=compile_midi_clips(p,std::array{track});CHECK(compiled[0][0].start==0&&compiled[0][0].end==72000);CHECK(compiled[0][1].start==72000&&compiled[0][1].end==120000);
    ProjectStore trimmed(p);trimmed.execute(SplitMidiClip{id,ppq,new_id()});compiled=compile_midi_clips(*trimmed.state().project,std::array{track});CHECK(compiled[0][0].end==24000&&compiled[0][1].start==24000);MidiPlayback scheduler;scheduler.prepare(compiled[0]); // shared boundary is off then on
}
void musical(){auto p=project();auto& m=*p.clips.front().midi;m.source_offset=240;m.notes[0].start=340;m.notes[0].length=390;m.notes[1].start=2400;m.events={{new_id(),240,2,0,64,127}};p.validate();const std::vector<Id> selected{m.notes[0].id},all{m.notes[0].id,m.notes[1].id};NoteEdit edit;edit.strength=50;edit.starts=true;edit.lengths=true;
    const auto half=transform_midi_notes(m,selected,edit);CHECK(half[0].start==290&&half[0].length==435&&half[1]==m.notes[1]);CHECK(half[0].id==m.notes[0].id&&half[0].channel==m.notes[0].channel);
    edit.strength=0;CHECK(transform_midi_notes(m,all,edit)==m.notes);edit.strength=100;edit.starts=false;CHECK(transform_midi_notes(m,selected,edit)[0].start==340);CHECK(transform_midi_notes(m,selected,edit)[0].length==480);
    edit.starts=true;edit.lengths=false;CHECK(transform_midi_notes(m,selected,edit)[0].start==240&&transform_midi_notes(m,selected,edit)[0].length==390);
    edit.kind=NoteEditKind::transpose;edit.value=127;auto transposed=transform_midi_notes(m,all,edit);CHECK(transposed[0].pitch==123&&transposed[1].pitch==127);edit.value=-127;transposed=transform_midi_notes(m,all,edit);CHECK(transposed[0].pitch==0&&transposed[1].pitch==4);CHECK(transform_midi_notes(m,{},edit)==m.notes);
    edit.kind=NoteEditKind::velocity;edit.mode=NoteValueMode::set;edit.value=0;CHECK(transform_midi_notes(m,all,edit)[0].velocity==1);edit.mode=NoteValueMode::scale;edit.value=50;CHECK(transform_midi_notes(m,all,edit)[0].velocity==64);edit.mode=NoteValueMode::add;edit.value=127;CHECK(transform_midi_notes(m,all,edit)[1].velocity==127);
    edit.kind=NoteEditKind::length;edit.mode=NoteValueMode::scale;edit.value=0;CHECK(transform_midi_notes(m,all,edit)[0].length==1);edit.mode=NoteValueMode::add;edit.value=-10000;CHECK(transform_midi_notes(m,all,edit)[0].length==1);edit.mode=NoteValueMode::set;edit.value=100000;const auto longNotes=transform_midi_notes(m,all,edit);CHECK(longNotes[0].start+longNotes[0].length==m.source_offset+m.length);
    ProjectStore store(p);edit.value=480;store.execute(EditMidiNotes{p.clips.front().id,all,edit});const auto after=*store.state().project;CHECK(after.clips.front().midi->events==m.events);CHECK(deserialize(serialize(after))==after);CHECK(store.undo()&&*store.state().project==p);CHECK(store.redo()&&*store.state().project==after);
    edit.kind=NoteEditKind::transpose;edit.value=.5;const auto revision=store.state().revision;rejects([&]{store.execute(EditMidiNotes{p.clips.front().id,all,edit});});CHECK(store.state().revision==revision);edit.value=1;rejects([&]{transform_midi_notes(m,std::array{Id{"missing"}},edit);});edit.kind=NoteEditKind::quantize;edit.grid=0;rejects([&]{transform_midi_notes(m,all,edit);});
    MidiClip edge;edge.source_offset=100;edge.length=100;edge.notes={{new_id(),90,130,127,127,0},{new_id(),199,1,0,1,15}};edit.grid=240;edit.strength=100;edit.starts=true;edit.lengths=true;const auto nearEdge=transform_midi_notes(edge,std::array{edge.notes[0].id,edge.notes[1].id},edit);for(const auto& n:nearEdge)CHECK(n.start>=0&&n.length>0&&n.start+n.length<=max_tick);CHECK(nearEdge[0].start+nearEdge[0].length<=220);
}
void controllers(){auto p=project();const auto id=p.clips.front().id;std::vector<MidiChannelEvent> events;for(int kind=2;kind<=6;++kind){MidiChannelEvent e{new_id(),ppq/2,kind,15,64,0};set_midi_event_value(e,kind==5?-1234:127);CHECK(midi_event_value(e)==(kind==5?-1234:127));events.push_back(e);}ProjectStore store(p);store.execute(SetMidiEvents{id,events});const auto after=*store.state().project;CHECK(after.clips.front().midi->notes==p.clips.front().midi->notes);CHECK(after.clips.front().midi->events==events);CHECK(deserialize(serialize(after))==after);CHECK(store.undo()&&*store.state().project==p);CHECK(store.redo()&&*store.state().project==after);
    const auto revision=store.state().revision;auto invalid=events;invalid[0].data2=128;rejects([&]{store.execute(SetMidiEvents{id,invalid});});CHECK(store.state().revision==revision);for(int v:{-8192,0,8191}){auto bend=events[3];set_midi_event_value(bend,v);CHECK(midi_event_value(bend)==v&&bend.data1>=0&&bend.data1<=127&&bend.data2>=0&&bend.data2<=127);}rejects([&]{set_midi_event_value(events[3],8192);});
    auto a=p.clips.front();a.midi->length=ppq;a.midi->events={{new_id(),0,2,0,64,127},{new_id(),0,5,0,1,70},{new_id(),ppq,5,0,2,75}};auto b=a;b.id=new_id();b.midi->start=ppq;for(auto& n:b.midi->notes)n.id=new_id();b.midi->events={{new_id(),0,2,0,64,127},{new_id(),0,5,0,5,80},{new_id(),0,3,0,12,0},{new_id(),0,4,0,44,0},{new_id(),0,6,0,60,99}};p.clips={b,a};p.validate();const auto compiled=compile_midi_events(p,std::array{p.tracks.front().id});MidiPlayback playback;playback.prepare({},compiled[0]);MidiBuffer buffer;allocations=0;probe=true;CHECK(playback.render(24000,128,true,buffer));probe=false;CHECK(allocations==0);int sustain=-1,bend=-1,program=-1,pressure=-1,poly=-1;for(const auto& e:buffer.view()){if(e.kind==MidiKind::cc&&e.data1==64)sustain=e.data2;if(e.kind==MidiKind::pitch_bend)bend=e.data1+128*e.data2;if(e.kind==MidiKind::program)program=e.data1;if(e.kind==MidiKind::pressure)pressure=e.data1;if(e.kind==MidiKind::poly_pressure)poly=e.data2;}CHECK(sustain==127&&bend==5+128*80&&program==12&&pressure==44&&poly==99);
    buffer.clear();CHECK(playback.render(48000,128,true,buffer));sustain=-1;bend=-1;for(const auto& e:buffer.view()){if(e.kind==MidiKind::cc&&e.data1==64)sustain=e.data2;if(e.kind==MidiKind::pitch_bend)bend=e.data1+128*e.data2;}CHECK(sustain==0&&bend==8192);buffer.clear();CHECK(playback.render(30000,128,true,buffer));bend=-1;for(const auto& e:buffer.view())if(e.kind==MidiKind::pitch_bend)bend=e.data1+128*e.data2;CHECK(bend==5+128*80);buffer.clear();CHECK(playback.render(30000,128,false,buffer));for(const auto& e:buffer.view()){if(e.kind==MidiKind::pitch_bend)CHECK(e.data1==0&&e.data2==64);if(e.kind==MidiKind::cc&&e.data1==64)CHECK(e.data2==0);}buffer.clear();CHECK(playback.render(0,128,true,buffer));
}
void controller_budget(){MidiRecorder recorder(0);for(int i=0;i<8144;++i){const bool sustain=i%32<16;recorder.capture(i,{0,sustain?MidiKind::cc:MidiKind::pitch_bend,static_cast<std::uint8_t>(i%16),static_cast<std::uint8_t>(sustain?64:1),static_cast<std::uint8_t>(sustain?127:70)});}recorder.advance(48000);CHECK(!recorder.fault());auto p=project();p.clips.front().midi=recorder.finish(Timeline(TimeMap{},48000));CHECK(p.clips.front().midi->events.size()==8160);p.validate();const auto compiled=compile_midi_events(p,std::array{p.tracks.front().id});CHECK(compiled[0].size()==8192);}
void schedule(){MidiPlayback p;p.prepare({{63,64,60,127,0},{64,128,60,100,0}});MidiBuffer b;CHECK(p.render(0,64,true,b));CHECK(b.size==1&&b.events[0].offset==63&&b.events[0].kind==MidiKind::note_on);b.clear();CHECK(p.render(64,64,true,b));CHECK(b.size==2&&b.events[0].kind==MidiKind::note_off&&b.events[1].kind==MidiKind::note_on);b.clear();CHECK(p.render(128,17,true,b)&&b.size==1&&b.events[0].kind==MidiKind::note_off);
    p.prepare({{0,200,60,127,0},{50,250,60,80,0}});b.clear();CHECK(p.render(100,17,true,b)&&b.size==1&&b.events[0].kind==MidiKind::note_on);b.clear();CHECK(p.render(0,17,true,b)&&b.size==2&&b.events[0].kind==MidiKind::note_off&&b.events[1].kind==MidiKind::note_on);b.clear();CHECK(p.render(17,17,false,b)&&b.size==1);b.clear();CHECK(p.render(17,17,false,b)&&b.size==0);b.clear();CHECK(p.render(17,17,true,b)&&b.size==1);
    std::vector<PlaybackMidiNote> crowded;for(int i=0;i<129;++i)crowded.push_back({0,100,static_cast<std::uint8_t>(i%128),100,static_cast<std::uint8_t>(i/128)});rejects([&]{p.prepare(crowded);});
    crowded.clear();for(int i=0;i<128;++i){crowded.push_back({0,96,static_cast<std::uint8_t>(i),100,0});crowded.push_back({96,192,static_cast<std::uint8_t>(i),100,0});}p.prepare(crowded);b.clear();CHECK(p.render(0,96,true,b)&&b.size==128);b.clear();CHECK(p.render(96,32,true,b)&&b.size==256);b.clear();CHECK(p.render(96,32,true,b)&&b.size==256); // loop/seek head: no duplicate obsolete offs
    crowded.clear();for(int i=0;i<300;++i)crowded.push_back({i*2,i*2+1,60,100,0});p.prepare(crowded);b.clear();allocations=0;probe=true;CHECK(!p.render(0,1024,true,b));probe=false;CHECK(allocations==0);
}
void engine(){for(auto workers:{1U,2U,4U}){auto e=std::make_shared<AudioEngine>();RenderGraph g;g.mixer.resize(2);g.inserts={synth(),{}};g.midi_notes={{{63,64,60,127,0},{64,128,60,127,0}}, {}};g.live_midi={true,false};e->prepare({48000,0,2,128,17,workers},g);std::array<float,256> out{};e->enqueue({ControlKind::play});allocations=0;probe=true;e->process(nullptr,out.data(),128);probe=false;CHECK(allocations==0);for(int f=0;f<128;++f)CHECK(out[f*2]==(f>=63?.25f:0.f));e->process(nullptr,out.data(),17);CHECK(out[0]==0);
        e->enqueue({ControlKind::seek,80});probe=true;e->process(nullptr,out.data(),17);probe=false;CHECK(allocations==0&&out[0]==.25f);e->enqueue({ControlKind::pause});e->process(nullptr,out.data(),17);CHECK(out[0]==0);e->enqueue({ControlKind::play});e->process(nullptr,out.data(),17);CHECK(out[0]==.25f);e->enqueue({ControlKind::stop});e->process(nullptr,out.data(),17);CHECK(out[0]==0);
        e->enqueue({ControlKind::seek,0});e->enqueue({ControlKind::loop,0,96});e->enqueue({ControlKind::play});e->process(nullptr,out.data(),128);for(int f=0;f<128;++f)CHECK(out[f*2]==(f>=63&&f<96?.25f:0.f));CHECK(!e->metrics().processing_fault);
    }
    auto e=std::make_shared<AudioEngine>();RenderGraph g;g.mixer.resize(3);g.inserts={synth(),{}, {}};g.live_midi={true,false,false};g.midi_notes={{{0,10000,60,127,0}}, {}, {}};g.outputs={2,2,no_mixer_track};g.buses={false,false,true};auto data=std::make_shared<AudioData>(sine_fixture(48000,2,10000,440));std::fill(data->samples.begin(),data->samples.end(),0.f);g.voices={{data,0,0,10000,{{0,0,1},{1,1,1}},{},1}};
    e->prepare({48000,0,2,128,128,4},g);AheadRenderer ahead(e,128,1024);ahead.start();CHECK(e->metrics().mixed_anticipation);e->enqueue({ControlKind::play});std::array<float,256> out{};probe=true;ahead.process(nullptr,out.data(),128);probe=false;CHECK(allocations==0&&out.back()==.25f&&!e->metrics().processing_fault);e->enqueue({ControlKind::seek,500});ahead.process(nullptr,out.data(),128);CHECK(out.back()==.25f);e->enqueue({ControlKind::stop});ahead.process(nullptr,out.data(),128);CHECK(out.back()==0);ahead.stop();
}
void audition(){for(auto workers:{1U,2U,4U}){auto e=std::make_shared<AudioEngine>();RenderGraph g;g.mixer.resize(1);g.inserts={synth()};g.live_midi={true};g.midi_monitor={false};e->prepare({48000,0,2,128,128,workers},g);const auto gen=e->midi_generation();std::array<float,256> out{};
    CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_on,0,60,127},0}));allocations=0;probe=true;e->process(nullptr,out.data(),128);probe=false;CHECK(allocations==0&&out.back()==.25f);
    CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_off,0,60,0},0}));e->process(nullptr,out.data(),128);CHECK(out.back()==0);
    CHECK(e->enqueue_audition_midi({gen-1,0,{0,MidiKind::note_on,0,60,127},0}));e->process(nullptr,out.data(),128);CHECK(out.back()==0);
    CHECK(e->enqueue_audition_midi({gen,9,{0,MidiKind::note_on,0,60,127},0}));e->process(nullptr,out.data(),128);CHECK(out.back()==0);
    for(int i=0;i<127;++i)CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_on,0,60,127},0}));CHECK(!e->enqueue_audition_midi({gen,0,{0,MidiKind::note_off,0,60,0},0}));e->process(nullptr,out.data(),128);CHECK(out.back()==0);
}}
void audition_tail(){for(auto rate:{44100U,48000U,96000U})for(auto workers:{1U,4U}){auto e=std::make_shared<AudioEngine>();RenderGraph g;g.mixer.resize(1);g.inserts={synth(rate)};g.live_midi={true};g.midi_monitor={true};e->prepare({rate,0,2,256,128,workers},g);const auto gen=e->midi_generation();std::array<float,512> out{};CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_on,0,60,127},0}));e->process(nullptr,out.data(),256);CHECK(out.back()==.25f);CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_off,0,60,0},0,70}));float last=.25f;bool faded=false;allocations=0;probe=true;for(unsigned block=0;block<rate/256/10+4;++block){e->process(nullptr,out.data(),256);for(std::size_t i=0;i<out.size();i+=2){CHECK(out[i]<=last+.000001f&&out[i]>=0&&last-out[i]<.001f);if(out[i]>.001f&&out[i]<.24f)faded=true;last=out[i];}}probe=false;CHECK(faded&&last==0&&allocations==0);CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_on,0,60,127},0}));e->process(nullptr,out.data(),256);CHECK(out.back()==.25f);CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_off,0,60,0},0,70}));e->process(nullptr,out.data(),256);CHECK(out.back()==.25f);CHECK(e->enqueue_live_midi({gen,0,{0,MidiKind::note_on,0,60,127},0}));e->process(nullptr,out.data(),256);CHECK(out.back()==.25f);CHECK(e->enqueue_live_midi({gen,0,{0,MidiKind::note_off,0,60,0},0}));e->process(nullptr,out.data(),256);CHECK(out.back()==0);CHECK(e->enqueue_live_midi({gen,0,{0,MidiKind::note_on,0,64,127},0}));CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_on,0,60,127},0}));e->process(nullptr,out.data(),256);CHECK(out.back()==.5f);CHECK(e->enqueue_audition_midi({gen,0,{0,MidiKind::note_off,0,60,0},0,70}));e->process(nullptr,out.data(),256);CHECK(out.back()==.25f);}}
void audition_not_recorded(){auto e=std::make_shared<AudioEngine>();RenderGraph g;g.mixer.resize(1);g.inserts={synth()};g.live_midi={true};auto recorder=std::make_shared<MidiRecorder>(0);g.midi_recordings={{0,recorder}};e->prepare({48000,0,2,128,128,2},g);const auto gen=e->midi_generation();std::array<float,256> out{};e->enqueue({ControlKind::play});e->enqueue_audition_midi({gen,0,{0,MidiKind::note_on,0,60,127},0});e->process(nullptr,out.data(),128);CHECK(out.back()==.25f);e->enqueue_audition_midi({gen,0,{0,MidiKind::note_off,0,60,0},0});e->process(nullptr,out.data(),128);CHECK(out.back()==0);const auto take=recorder->finish(Timeline(TimeMap{},48000));CHECK(take.notes.empty()&&take.events.empty());}
void application(const std::filesystem::path& fixture){Directory dir;const auto plugin=dir.path/"instrument.vst3";std::filesystem::copy_file(fixture,plugin);auto u=plugin.u8string();auto info=probe_vst3(std::string(u.begin(),u.end())).front();NativeInsert fx;fx.id=new_id();fx.kind=InsertKind::vst3;fx.plugin_path=info.path;fx.class_id=info.class_id;fx.plugin_name=info.name;
    Application a;a.new_project();auto track=a.add_instrument_track("Keys");a.set_inserts(track,{fx});a.connect(std::make_unique<ManualDevice>(),{0,48000,128,{}, {0,1},2});auto clip=a.create_midi_clip(track,0,4*ppq);a.set_midi_notes(clip,{{new_id(),0,ppq,60,127,0}});auto time=a.services().projects->state().project->time;time.tempos={{0,60}};a.set_time_map(time);CHECK(a.services().projects->state().project->clips.front().midi->length==4*ppq);CHECK(a.undo());CHECK(a.redo());CHECK(a.undo());a.play();std::array<float,256> out{};a.engine()->process(nullptr,out.data(),128);CHECK(out.back()>.2f);rejects([&]{a.remove_clip(clip);});a.pause();a.engine()->process(nullptr,out.data(),128);a.poll();CHECK(out.back()==0);a.seek(24000);a.engine()->process(nullptr,out.data(),128);a.poll();a.split_clip(clip,24000);CHECK(a.services().projects->state().project->clips.size()==2);CHECK(a.undo());CHECK(a.redo());CHECK(a.undo());a.duplicate_clip(clip);CHECK(a.undo());
    const auto file=dir.path/"song.mrsproject";a.save_project(file);a.save_project(dir.path/"copy"/"song.mrsproject");a.open_project(file);CHECK(a.services().projects->state().project->clips[0].midi->notes.size()==1);a.connect(std::make_unique<ManualDevice>(),{0,48000,128,{}, {0,1},2});a.play();a.engine()->process(nullptr,out.data(),128);check(out.back()>.2f,"reopened MIDI clip audio");a.pause();a.engine()->process(nullptr,out.data(),128);a.poll();auto audioTrack=a.add_audio_track("Raw input");a.set_track_input(audioTrack,0);a.connect(std::make_unique<ManualDevice>(),{0,48000,128,{0}, {0,1},2});a.set_track_armed(audioTrack,true);a.start_recording(dir.path/"raw.wav");std::array<float,128> input;input.fill(.125f);a.engine()->process(input.data(),out.data(),128);a.stop_recording();CHECK(a.services().projects->state().project->clips.size()==2);auto raw=open_wav(dir.path/"raw.wav");CHECK(raw.frames()==128&&std::abs(raw.samples[0]-.125f)<.00001f);a.disconnect();
}
}
void* operator new(std::size_t n){if(probe)++allocations;if(auto p=std::malloc(n?n:1))return p;throw std::bad_alloc{};}void operator delete(void* p)noexcept{std::free(p);}void operator delete(void* p,std::size_t)noexcept{std::free(p);}
int main(int argc,char** argv){try{CHECK(argc==2);model();musical();controllers();controller_budget();schedule();engine();audition();audition_tail();audition_not_recorded();application(argv[1]);std::cout<<"PASS MIDI clips\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
