#include <mrs/desktop.hpp>
#include <mrs/vst3.hpp>
#include <mrs/ahead_renderer.hpp>
#include <iostream>
#include <cmath>
#include <new>
#include <cstdlib>
#include <thread>
namespace {
using namespace mrs;using namespace mrs::audio;using namespace mrs::processing;using namespace mrs::desktop;
thread_local bool probe{};unsigned allocations{};
void check(bool value,const char* text){if(!value)throw std::runtime_error(text);}
#define CHECK(...) check(static_cast<bool>((__VA_ARGS__)),#__VA_ARGS__)
template<class F>void rejects(F f){bool caught=false;try{f();}catch(const std::exception&){caught=true;}CHECK(caught);}
struct Directory{std::filesystem::path path=std::filesystem::temp_directory_path()/("mrs-midi-record-"+new_id().value);Directory(){std::filesystem::create_directory(path);}~Directory(){std::error_code e;std::filesystem::remove_all(path,e);}};
struct Device final:IAudioDevice {DevicePhase phase{DevicePhase::closed};std::vector<DeviceInfo> enumerate()override{return {{0,"Record fixture",{"Mic"},{"L","R"},16,8192,128,1}};}void control_panel(int)override{}void open(const DeviceConfig&,std::shared_ptr<AudioEngine>)override{phase=DevicePhase::open;}void start()override{phase=DevicePhase::running;}void stop()override{phase=DevicePhase::stopped;}void close()noexcept override{phase=DevicePhase::closed;}DeviceStatus status()override{return {phase,48000};}};
void capture(){
 CHECK(midi_record_sample(48000,0,1000000000,900000000,48000)==43200);
 CHECK(midi_record_sample(100,80,1000000000,900000000,48000)==80);
 CHECK(midi_record_sample(100,0,1000000000,0,48000)==100);
 MidiRecorder recorder(4800);const Timeline time(TimeMap{},48000);
 recorder.capture(4800,{0,MidiKind::note_on,1,60,100});recorder.capture(9600,{0,MidiKind::cc,1,64,127});recorder.capture(12000,{0,MidiKind::pitch_bend,1,0,80});recorder.capture(14400,{0,MidiKind::note_off,1,60,0});recorder.capture(15000,{0,MidiKind::note_on,2,67,90});recorder.advance(24000);
 const auto clip=recorder.finish(time);CHECK(clip.notes.size()==2&&clip.events.size()==3);CHECK(clip.start==time.to_ticks(4800));CHECK(clip.notes[0].length==time.to_ticks(14400)-time.to_ticks(4800));CHECK(clip.notes[1].length==clip.length-clip.notes[1].start);CHECK(clip.events.back().data1==64&&clip.events.back().data2==0&&clip.events.back().start==clip.length);
 Project p;p.id=new_id();Track t;t.id=new_id();t.kind=TrackKind::instrument;t.name="Keys";p.tracks={t};Clip c;c.id=new_id();c.track=t.id;c.name="Take";c.midi=clip;p.clips={c};p.validate();CHECK(deserialize(serialize(p))==p);ProjectStore store(p);store.execute(DuplicateClip{c.id,new_id()});CHECK(store.state().project->clips[1].midi->events[0].id!=clip.events[0].id);CHECK(store.undo());
 auto old=serialize(p);auto at=old.find("MIDIEVENTS ");const auto end=old.find("MARKERS",at);old.erase(at,end-at);old.replace(0,std::string("MRS_CORE_SNAPSHOT 13").size(),"MRS_CORE_SNAPSHOT 12");auto migrated=deserialize(old);CHECK(migrated.clips[0].midi->events.empty()&&migrated.clips[0].midi->notes==clip.notes);
 auto notes=compile_midi_clips(p,std::span<const Id>(&t.id,1));auto events=compile_midi_events(p,std::span<const Id>(&t.id,1));MidiPlayback playback;playback.prepare(notes[0],events[0]);MidiBuffer buffer;probe=true;CHECK(playback.render(13000,100,true,buffer));probe=false;CHECK(allocations==0);CHECK(std::any_of(buffer.view().begin(),buffer.view().end(),[](const auto& e){return e.kind==MidiKind::pitch_bend&&e.data2==80;}));buffer.clear();CHECK(playback.render(13100,100,false,buffer));CHECK(std::any_of(buffer.view().begin(),buffer.view().end(),[](const auto& e){return e.kind==MidiKind::cc&&e.data1==64&&e.data2==0;}));
 MidiRecorder dense(0);for(std::size_t i=0;i<MidiRecorder::capacity+1;++i)dense.capture(static_cast<Sample>(i),{0,MidiKind::cc,0,1,1});CHECK(dense.fault());
}
void preview(){MidiRecorder recorder(0);std::atomic<bool> done{};std::thread producer([&]{for(int i=0;i<2000;++i){recorder.capture(i*24,{0,MidiKind::note_on,0,60,100});recorder.capture(i*24+12,{0,MidiKind::note_off,0,60,0});recorder.advance(i*24+24);}done.store(true,std::memory_order_release);});bool valid=true;do{const auto take=recorder.preview(Timeline(TimeMap{},48000));valid=valid&&take.notes.size()<=2000&&std::all_of(take.notes.begin(),take.notes.end(),[](const auto& n){return n.pitch==60&&n.velocity==100&&n.length>0;});}while(!done.load(std::memory_order_acquire));producer.join();CHECK(valid);const auto before=recorder.preview(Timeline(TimeMap{},48000)),after=recorder.finish(Timeline(TimeMap{},48000));CHECK(before.notes.size()==after.notes.size()&&before.length==after.length);}
void ordering(){
 MidiPlayback playback;playback.prepare({},{{0,{0,MidiKind::cc,0,1,100}},{100,{0,MidiKind::pitch_bend,0,0,70}}});MidiBuffer buffer;buffer.push({0,MidiKind::note_on,0,60,100});buffer.push({0,MidiKind::note_off,0,60,0});CHECK(playback.render(0,64,true,buffer));CHECK(buffer.events[0].kind==MidiKind::note_on&&buffer.events[1].kind==MidiKind::note_off);for(const auto& e:buffer.view())CHECK(e.offset<64);
 std::vector<PlaybackMidiEvent> burst;for(int i=0;i<300;++i)burst.push_back({0,{0,MidiKind::cc,0,1,static_cast<std::uint8_t>(i%128)}});burst.push_back({129,{0,MidiKind::cc,0,1,55}});playback.prepare({},burst);buffer.clear();CHECK(!playback.render(0,128,true,buffer));buffer.clear();CHECK(playback.render(128,128,true,buffer));CHECK(buffer.size==1&&buffer.events[0].offset==1&&buffer.events[0].data2==55);
 Project p;p.id=new_id();Track t;t.id=new_id();t.kind=TrackKind::instrument;t.name="Trim";p.tracks={t};Clip c;c.id=new_id();c.track=t.id;c.name="Controls";c.midi=MidiClip{};c.midi->source_offset=ppq;c.midi->events={{new_id(),0,2,0,64,127},{new_id(),ppq,2,0,64,0}};p.clips={c};p.validate();const auto controls=compile_midi_events(p,std::span<const Id>(&t.id,1));playback.prepare({},controls[0]);buffer.clear();CHECK(playback.render(0,128,true,buffer));int sustain=-1;for(const auto& e:buffer.view())if(e.kind==MidiKind::cc&&e.data1==64)sustain=e.data2;CHECK(sustain==0);
}
void transitions(){
 for(const unsigned workers:{1U,2U,4U}){auto engine=std::make_shared<AudioEngine>();auto recorder=std::make_shared<MidiRecorder>(0);RenderGraph graph;graph.mixer.resize(2);graph.live_midi={true,false};graph.midi_recordings={{0,recorder}};graph.outputs={no_mixer_track,no_mixer_track};auto data=std::make_shared<AudioData>(sine_fixture(48000,2,2048,440));graph.voices={{data,0,0,2048,{{0,0,1},{1,1,1}},{},1}};engine->prepare({48000,0,2,128,17,workers},graph);AheadRenderer ahead(engine,128,1024);ahead.start();engine->enqueue({ControlKind::play});engine->enqueue_live_midi({engine->midi_generation()-1,0,{0,MidiKind::note_on,0,10,100}});engine->enqueue_live_midi({engine->midi_generation(),0,{0,MidiKind::note_on,0,60,100}});std::array<float,256> out{};probe=true;ahead.process(nullptr,out.data(),128);probe=false;CHECK(allocations==0);engine->midi_input_lost();ahead.process(nullptr,out.data(),128);ahead.stop();CHECK(recorder->fault());const auto take=recorder->finish(Timeline(TimeMap{},48000));CHECK(take.notes.size()==1&&take.notes[0].pitch==60&&take.notes[0].length>0);}
 MidiRecorder cut(0);cut.capture(0,{0,MidiKind::note_on,0,60,100});cut.capture(100,{0,MidiKind::cc,0,64,127});cut.cut(24000);cut.advance(48000);const auto result=cut.finish(Timeline(TimeMap{},48000));CHECK(result.notes.front().length==ppq&&result.events.back().data2==0&&result.events.back().start==ppq);
 MidiRecorder instant(0);instant.capture(0,{0,MidiKind::note_on,0,60,100});instant.capture(0,{0,MidiKind::note_off,0,60,0});instant.advance(128);CHECK(instant.finish(Timeline(TimeMap{},48000)).notes.empty());
}
void application(const std::filesystem::path& fixture){
 Directory dir;const auto plugin=dir.path/"instrument.vst3";std::filesystem::copy_file(fixture,plugin);const auto u=plugin.u8string();const auto info=probe_vst3(std::string(u.begin(),u.end())).front();NativeInsert fx;fx.id=new_id();fx.kind=InsertKind::vst3;fx.plugin_path=info.path;fx.class_id=info.class_id;fx.plugin_name=info.name;
 for(const bool combined:{false,true})for(const bool monitor:{false,true}){
 Application app;app.new_project();const auto track=app.add_instrument_track("Keys");app.set_inserts(track,{fx});app.set_midi_input(track,"fixture:unavailable",-1,monitor);app.set_track_armed(track,true);std::optional<Id> audio;
 if(combined){audio=app.add_audio_track("Raw");app.set_track_input(*audio,0);app.set_track_armed(*audio,true);}
 app.connect(std::make_unique<Device>(),{0,48000,128,combined?std::vector<int>{0}:std::vector<int>{}, {0,1},4});app.start_recording(dir.path/("raw-"+std::to_string(monitor)+".wav"));CHECK(app.recording());rejects([&]{app.seek(0);});rejects([&]{app.undo();});
 std::array<float,256> out{};std::array<float,128> in;in.fill(.125f);app.engine()->process(combined?in.data():nullptr,out.data(),128);const auto generation=app.engine()->midi_generation();CHECK(app.engine()->enqueue_live_midi({generation,0,{0,MidiKind::note_on,0,60,127}}));CHECK(app.engine()->enqueue_live_midi({generation,0,{0,MidiKind::cc,0,64,127}}));CHECK(app.engine()->enqueue_live_midi({generation,0,{0,MidiKind::pitch_bend,0,0,75}}));probe=true;app.engine()->process(combined?in.data():nullptr,out.data(),128);probe=false;CHECK(allocations==0);if(monitor)CHECK(out.back()>.2f);else CHECK(std::abs(out.back())<.01f);
 const auto livePreview=app.midi_recording_preview();CHECK(livePreview.size()==1&&livePreview.front().track==track&&livePreview.front().midi->notes.size()==1&&livePreview.front().midi->notes.front().length>0);CHECK(app.services().projects->state().project->clips.empty());app.engine()->process(combined?in.data():nullptr,out.data(),128);CHECK(app.stop_recording());CHECK(app.midi_recording_preview().empty());CHECK(!app.recording());const auto project=app.services().projects->state().project;CHECK(project->clips.size()==(combined?2U:1U));const auto midi=std::find_if(project->clips.begin(),project->clips.end(),[](const auto& c){return c.midi.has_value();});CHECK(midi!=project->clips.end()&&midi->midi->notes.size()==1);CHECK(midi->midi->notes[0].velocity==127&&midi->midi->events.size()>=3);const auto expected=*project;CHECK(app.undo());CHECK(app.services().projects->state().project->clips.empty());CHECK(app.redo());CHECK(*app.services().projects->state().project==expected);
 if(combined){const auto raw=open_wav(dir.path/("raw-"+std::to_string(monitor)+".wav"));CHECK(raw.frames()==384&&raw.samples[0]==.125f);}
 const auto file=dir.path/("song-"+std::to_string(combined)+std::to_string(monitor)+".mrsproject");app.save_project(file);const auto saved=persistence::load_project(file).project;app.open_project(file);CHECK(*app.services().projects->state().project==saved);const auto restored=app.services().projects->state().project;const auto restored_midi=std::find_if(restored->clips.begin(),restored->clips.end(),[](const auto& c){return c.midi.has_value();});CHECK(restored_midi->midi==midi->midi&&restored_midi->id==midi->id);app.connect(std::make_unique<Device>(),{0,48000,128,{}, {0,1},2});app.seek(128);app.engine()->process(nullptr,out.data(),128);app.play();app.engine()->process(nullptr,out.data(),128);CHECK(out.back()>.2f);app.stop();app.engine()->process(nullptr,out.data(),128);CHECK(std::abs(out.back())<.01f);app.disconnect();
 }
}
}
void* operator new(std::size_t n){if(probe)++allocations;if(auto p=std::malloc(n?n:1))return p;throw std::bad_alloc{};}void operator delete(void* p)noexcept{std::free(p);}void operator delete(void* p,std::size_t)noexcept{std::free(p);}
int main(int argc,char** argv){try{CHECK(argc==2);capture();preview();ordering();transitions();application(argv[1]);std::cout<<"PASS MIDI recording\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
