#pragma once
#include "Desktop.h"
#include <sstream>
#include <set>
namespace ui {
class ControllerPanel final : public juce::Component, private juce::Timer {
public:
    ControllerPanel(Desktop& d,mrs::Id clipId):owner(d),id(std::move(clipId)),graph(*this){
        setLookAndFeel(&owner.theme);setName("MIDI controller events");
        const std::array<juce::String,5> types{"CC / sustain","Program (0..127)","Channel pressure","Pitch bend (-8192..8191)","Poly pressure"};for(std::size_t i=0;i<types.size();++i)kind.addItem(types[i],static_cast<int>(i)+2);kind.setSelectedId(2);
        for(int ch=1;ch<=16;++ch)channel.addItem("Channel "+juce::String(ch),ch);channel.setSelectedId(1);number.setText("64");position.setText("0");value.setText("0");
        snap.addItem("Snap off",1);snap.addItem("1/4",2);snap.addItem("1/8",3);snap.addItem("1/16",4);snap.addItem("1/32",5);snap.setSelectedId(4);
        std::array<juce::Component*,12> controls{&kind,&channel,&number,&position,&value,&snap,&selector,&add,&apply,&remove,&graph,&hint};for(auto* c:controls)addAndMakeVisible(c);
        kind.setComponentID("controller-kind");channel.setComponentID("controller-channel");number.setComponentID("controller-number");position.setComponentID("controller-position");value.setComponentID("controller-value");selector.setComponentID("controller-selector");add.setComponentID("controller-add");apply.setComponentID("controller-apply");remove.setComponentID("controller-delete");graph.setComponentID("controller-lane");
        kind.setTitle("MIDI event type");channel.setTitle("MIDI channel");number.setTitle("CC number / poly pressure note (0..127)");position.setTitle("Source position in quarter-note beats");value.setTitle("MIDI value / signed pitch bend");selector.setTitle("All recorded controller events");snap.setTitle("Controller position snap");
        const std::array<juce::String,5> names{"Event type","Channel","CC / note #","Source beat","Value"};for(std::size_t i=0;i<labels.size();++i){labels[i].setText(names[i],juce::dontSendNotification);labels[i].setFont(owner.theme.font(12));addAndMakeVisible(labels[i]);}
        for(auto* field:{&number,&position,&value})field->setFont(owner.theme.font(13));hint.setFont(owner.theme.font(12));hint.setJustificationType(juce::Justification::topLeft);
        kind.onChange=channel.onChange=[this]{cancel();selection.clear();selected.reset();apply.setEnabled(false);remove.setEnabled(false);number.setEnabled(kind.getSelectedId()==2||kind.getSelectedId()==6);graph.repaint();};number.onTextChange=[this]{graph.repaint();};selector.onChange=[this]{cancel();loadSelected();if(selected)selection={selected->value};};
        add.onClick=[this]{edit(0);};apply.onClick=[this]{edit(1);};remove.onClick=[this]{edit(2);};reload();setSize(900,500);startTimer(150);
    }
    ~ControllerPanel() override{setLookAndFeel(nullptr);}
    void activate(mrs::Id next){cancel();id=std::move(next);selected.reset();selection.clear();setEnabled(true);reload();}
    void setEmbedded(){embedded=true;resized();}
    void resized() override{const int width=(getWidth()-32)/5;std::array<juce::Component*,5> fields{&kind,&channel,&number,&position,&value};for(std::size_t i=0;i<fields.size();++i){const int x=16+static_cast<int>(i)*width;labels[i].setBounds(x,8,width-8,20);fields[i]->setBounds(x,30,width-8,28);}selector.setBounds(16,68,getWidth()-32,28);snap.setBounds(16,104,120,26);add.setBounds(146,104,110,26);apply.setBounds(266,104,110,26);remove.setBounds(386,104,110,26);graph.setBounds(16,140,getWidth()-32,getHeight()-(embedded?166:216));hint.setBounds(16,getHeight()-(embedded?24:68),getWidth()-32,embedded?20:60);}
    void paint(juce::Graphics& g) override{g.fillAll(juce::Colour(background));}
    bool keyPressed(const juce::KeyPress& key) override{if(key==juce::KeyPress::escapeKey){cancel();return true;}if(key.getModifiers().isCtrlDown()&&(key.getKeyCode()=='Z'||key.getKeyCode()=='Y')){cancel();owner.run([&]{if(key.getKeyCode()=='Y'||key.getModifiers().isShiftDown())owner.app.redo();else owner.app.undo();owner.refresh();});reload();return true;}if(key.getKeyCode()==juce::KeyPress::deleteKey){edit(2);return true;}return false;}
    void setTimeView(double first,double length){viewFirst=first;viewLength=length;if(!dragging&&!selecting){const auto p=owner.project();const auto at=std::find_if(p->clips.begin(),p->clips.end(),[&](const auto& c){return c.id==id;});if(at!=p->clips.end()&&at->midi&&*at->midi!=clip)reload();}graph.repaint();}
private:
    double viewFirst{},viewLength{};bool embedded{};
    struct Graph final : juce::Component {
        explicit Graph(ControllerPanel& p):owner(p){setWantsKeyboardFocus(true);setName("Controller lane");}
        ControllerPanel& owner;
        void paint(juce::Graphics& g) override{owner.paintLane(g);}
        void mouseDown(const juce::MouseEvent& e) override{grabKeyboardFocus();owner.laneDown(e);}
        void mouseDrag(const juce::MouseEvent& e) override{owner.laneDrag(e);}
        void mouseUp(const juce::MouseEvent&) override{owner.laneUp();}
        void mouseDoubleClick(const juce::MouseEvent& e) override{owner.cancel();owner.position.setText(juce::String(static_cast<double>(owner.tickAt(e.position.x))/mrs::ppq,6));owner.value.setText(juce::String(owner.valueAt(e.position.y)));owner.edit(0);}
        void focusLost(FocusChangeType) override{owner.cancel();}
        bool keyPressed(const juce::KeyPress& k) override{return owner.keyPressed(k);}
    };
    Desktop& owner;mrs::Id id;Graph graph;juce::ComboBox kind,channel,snap,selector;juce::TextEditor number,position,value;std::array<juce::Label,5> labels;juce::TextButton add{"Add event"},apply{"Apply"},remove{"Delete"};juce::Label hint;
    mrs::MidiClip clip,baseline;std::vector<mrs::MidiChannelEvent> events;std::optional<mrs::Id> selected;bool dragging{},selecting{};std::set<std::string> selection,initialSelection;juce::Point<float> origin;juce::Rectangle<float> selectionBox;mrs::Id dragAnchor;
    const mrs::MidiClip& current(const mrs::Project& p) const{const auto at=std::find_if(p.clips.begin(),p.clips.end(),[&](const auto& c){return c.id==id;});if(at==p.clips.end()||!at->midi)throw std::runtime_error("MIDI clip no longer exists");return *at->midi;}
    static double numberValue(const juce::TextEditor& field){std::istringstream in(field.getText().toStdString());in.imbue(std::locale::classic());double v{};if(!(in>>v)||!std::isfinite(v))throw std::invalid_argument("Enter a finite number");in>>std::ws;if(!in.eof())throw std::invalid_argument("Unexpected characters in field");return v;}
    bool matches(const mrs::MidiChannelEvent& e) const{const int n=number.getText().getIntValue();return e.kind==kind.getSelectedId()&&e.channel==channel.getSelectedId()-1&&((e.kind!=2&&e.kind!=6)||e.data1==n);}
    void reload(){try{const auto p=owner.project();clip=current(*p);events=clip.events;selector.clear(juce::dontSendNotification);int chosen=0;for(std::size_t i=0;i<events.size();++i){const auto& e=events[i];selector.addItem("Beat "+juce::String(static_cast<double>(e.start)/mrs::ppq,3)+" | "+kind.getItemText(e.kind-2)+" | ch "+juce::String(e.channel+1)+" | # "+juce::String(e.data1)+" | value "+juce::String(mrs::midi_event_value(e)),static_cast<int>(i)+1);if(selected&&*selected==e.id)chosen=static_cast<int>(i)+1;}selector.setTextWhenNothingSelected("All events - choose one, or add to the displayed lane");selector.setSelectedId(chosen,juce::dontSendNotification);if(!chosen)selected.reset();else loadSelected();std::erase_if(selection,[&](const auto& value){return std::none_of(events.begin(),events.end(),[&](const auto& e){return e.id.value==value;});});apply.setEnabled(selected.has_value());remove.setEnabled(selected.has_value()||!selection.empty());graph.repaint();hint.setText("Double click: add. Left drag empty space: select. Drag selected points: one Undo. Delete: selected points.\nChoose an event above to show its lane. CC64: 0-63 off, 64-127 on. Program is MIDI 0-127.\nSource beats include trim offset. Pause/Stop before editing. Ctrl+Z/Y in lane: Undo/Redo.",juce::dontSendNotification);}catch(const std::exception& e){hint.setText(juce::String::fromUTF8(e.what()),juce::dontSendNotification);setEnabled(false);}}
    void loadSelected(){const int at=selector.getSelectedId()-1;if(at<0||at>=static_cast<int>(events.size()))return;const auto& e=events[static_cast<std::size_t>(at)];selected=e.id;kind.setSelectedId(e.kind,juce::dontSendNotification);channel.setSelectedId(e.channel+1,juce::dontSendNotification);number.setText(juce::String(e.kind==2||e.kind==6?e.data1:0));position.setText(juce::String(static_cast<double>(e.start)/mrs::ppq,6));value.setText(juce::String(mrs::midi_event_value(e)));number.setEnabled(e.kind==2||e.kind==6);apply.setEnabled(true);remove.setEnabled(true);graph.repaint();}
    void edit(int operation){try{cancel();const auto p=owner.project();auto next=current(*p).events;auto at=std::find_if(next.begin(),next.end(),[&](const auto& e){return selected&&e.id==*selected;});if(operation!=0&&at==next.end()&&(operation!=2||selection.empty()))throw std::invalid_argument("Select an event");if(operation==2){std::erase_if(next,[&](const auto& e){return selection.contains(e.id.value)||(selected&&e.id==*selected);});selected.reset();selection.clear();}else{mrs::MidiChannelEvent e;e.id=operation==0?mrs::new_id():at->id;e.kind=kind.getSelectedId();e.channel=channel.getSelectedId()-1;const auto beat=numberValue(position),v=numberValue(value);if(beat<0||beat>static_cast<double>(mrs::max_tick)/mrs::ppq||v<-8192||v>8191||std::floor(v)!=v)throw std::invalid_argument("Position/value outside range");e.start=static_cast<mrs::Tick>(std::llround(beat*mrs::ppq));if(e.kind==2||e.kind==6){const auto n=numberValue(number);if(n<0||n>127||std::floor(n)!=n)throw std::invalid_argument("CC/note must be 0..127");e.data1=static_cast<int>(n);}mrs::set_midi_event_value(e,static_cast<int>(v));if(operation==0)next.push_back(e);else *at=e;selected=e.id;selection={e.id.value};}owner.app.set_midi_events(id,std::move(next));owner.refresh();reload();}catch(const std::exception& e){hint.setText(juce::String::fromUTF8(e.what()),juce::dontSendNotification);}}
    juce::Rectangle<float> plot() const{return juce::Rectangle<float>{viewLength>0?64.f:45.f,26.f,static_cast<float>(graph.getWidth())-(viewLength>0?80.f:90.f),static_cast<float>(graph.getHeight())-52.f};}
    juce::Point<float> point(const mrs::MidiChannelEvent& e) const{auto r=plot();const double low=e.kind==5?-8192.:0.,range=e.kind==5?16383.:127.;return {r.getX()+static_cast<float>(static_cast<double>(e.start-(viewLength>0?viewFirst:clip.source_offset))/(viewLength>0?viewLength:clip.length))*r.getWidth(),r.getBottom()-static_cast<float>((mrs::midi_event_value(e)-low)/range)*r.getHeight()};}
    mrs::Tick tickAt(float x) const{auto r=plot();const std::array<mrs::Tick,5> grids{0,mrs::ppq,mrs::ppq/2,mrs::ppq/4,mrs::ppq/8};const auto grid=grids[static_cast<std::size_t>(snap.getSelectedId()-1)];auto tick=static_cast<mrs::Tick>(std::llround((x-r.getX())/r.getWidth()*(viewLength>0?viewLength:clip.length)));if(grid)tick=static_cast<mrs::Tick>(std::llround(static_cast<double>(tick)/grid))*grid;return std::clamp(static_cast<mrs::Tick>(viewLength>0?viewFirst:clip.source_offset)+tick,clip.source_offset,clip.source_offset+clip.length);}
    int valueAt(float y) const{const auto r=plot();const double low=kind.getSelectedId()==5?-8192.:0.,range=kind.getSelectedId()==5?16383.:127.;return static_cast<int>(std::llround(low+juce::jlimit(0.,1.,static_cast<double>((r.getBottom()-y)/r.getHeight()))*range));}
    void paintLane(juce::Graphics& g){g.fillAll(juce::Colour(surface));auto r=plot();g.setFont(owner.theme.font(11));g.setColour(juce::Colours::lightgrey);g.drawText(kind.getText()+" / ch "+juce::String(channel.getSelectedId())+" / # "+number.getText(),0,0,graph.getWidth(),20,juce::Justification::centred);for(int i=0;i<=4;++i){const float y=r.getY()+i*r.getHeight()/4;g.setColour(juce::Colours::lightgrey);const int v=kind.getSelectedId()==5?8191-static_cast<int>(std::lround(i*16383./4)):127-static_cast<int>(std::lround(i*127./4));g.drawText(juce::String(v),0,static_cast<int>(y)-8,40,16,juce::Justification::centredRight);const auto tick=static_cast<mrs::Tick>((viewLength>0?viewFirst:clip.source_offset)+(viewLength>0?viewLength:clip.length)*i/4);g.drawText(juce::String(static_cast<double>(tick+(viewLength>0?clip.start-clip.source_offset:0))/mrs::ppq,2),juce::jlimit(0,juce::jmax(0,graph.getWidth()-50),static_cast<int>(r.getX()+i*r.getWidth()/4)-18),graph.getHeight()-22,50,18,juce::Justification::centred);}g.saveState();g.reduceClipRegion(r.expanded(5).toNearestInt());std::vector<const mrs::MidiChannelEvent*> lane;for(const auto& e:events)if(matches(e)&&e.start>=clip.source_offset&&e.start<=clip.source_offset+clip.length)lane.push_back(&e);std::stable_sort(lane.begin(),lane.end(),[](auto a,auto b){return a->start<b->start;});juce::Point<float> last;bool have=false;for(const auto* e:lane){const auto p=point(*e);g.setColour(juce::Colours::skyblue);if(have){if(e->kind==3||(e->kind==2&&(e->data1==64||e->data1==65||e->data1==66))){g.drawLine(last.x,last.y,p.x,last.y,1);g.drawLine(p.x,last.y,p.x,p.y,1);}else g.drawLine(last.x,last.y,p.x,p.y,1);}g.setColour(selection.contains(e->id.value)||(selected&&*selected==e->id)?juce::Colours::white:juce::Colours::skyblue);g.fillEllipse(p.x-4,p.y-4,8,8);last=p;have=true;}if(viewLength>0){const auto p=owner.project();const auto head=mrs::Timeline(p->time,p->sample_rate).to_ticks(owner.app.engine()->state().sample);g.setColour(juce::Colours::white);g.drawVerticalLine(static_cast<int>(r.getX()+(head-clip.start+clip.source_offset-viewFirst)/viewLength*r.getWidth()),r.getY(),r.getBottom());}g.restoreState();if(selecting){g.setColour(juce::Colours::skyblue.withAlpha(.12f));g.fillRect(selectionBox);g.setColour(juce::Colours::skyblue);g.drawRect(selectionBox,1.f);}if(graph.hasKeyboardFocus(true)){g.setColour(juce::Colours::skyblue);g.drawRect(graph.getLocalBounds(),1);}}
    void laneDown(const juce::MouseEvent& e){cancel();if(!e.mods.isLeftButtonDown()||!plot().expanded(5).contains(e.position))return;try{if(owner.app.recording()||owner.app.engine()->state().playback==mrs::PlaybackState::playing)throw std::runtime_error("Pause/Stop before editing");const auto p=owner.project();clip=current(*p);events=clip.events;origin=e.position;for(auto it=events.rbegin();it!=events.rend();++it)if(matches(*it)&&point(*it).getDistanceFrom(e.position)<9){if(e.mods.isCtrlDown()||e.mods.isShiftDown()){if(selection.contains(it->id.value)){selection.erase(it->id.value);selected.reset();graph.repaint();return;}selection.insert(it->id.value);}else if(!selection.contains(it->id.value))selection={it->id.value};selected=it->id;dragAnchor=it->id;reload();baseline=clip;dragging=true;return;}initialSelection=(e.mods.isCtrlDown()||e.mods.isShiftDown())?selection:std::set<std::string>{};selection=initialSelection;selected.reset();selector.setSelectedId(0,juce::dontSendNotification);apply.setEnabled(false);remove.setEnabled(!selection.empty());selecting=true;selectionBox={origin,origin};graph.repaint();}catch(const std::exception& ex){hint.setText(juce::String::fromUTF8(ex.what()),juce::dontSendNotification);}}
    void laneDrag(const juce::MouseEvent& e){if(selecting){selectionBox=juce::Rectangle<float>(origin,e.position).getIntersection(plot());selection=initialSelection;for(const auto& event:events)if(matches(event)&&selectionBox.expanded(.5f).contains(point(event)))selection.insert(event.id.value);remove.setEnabled(!selection.empty());graph.repaint();return;}if(!dragging)return;events=baseline.events;const auto anchor=std::find_if(events.begin(),events.end(),[&](const auto& event){return event.id==dragAnchor;});if(anchor==events.end())return;const auto destination=point(*anchor)+(e.position-origin);auto dt=tickAt(destination.x)-anchor->start;int dv=valueAt(destination.y)-mrs::midi_event_value(*anchor);mrs::Tick low=-mrs::max_tick,high=mrs::max_tick;int vlow=-16383,vhigh=16383;for(const auto& event:events)if(selection.contains(event.id.value)){low=std::max(low,clip.source_offset-event.start);high=std::min(high,clip.source_offset+clip.length-event.start);const int v=mrs::midi_event_value(event);vlow=std::max(vlow,(event.kind==5?-8192:0)-v);vhigh=std::min(vhigh,(event.kind==5?8191:127)-v);}dt=std::clamp(dt,low,std::max(low,high));dv=std::clamp(dv,vlow,std::max(vlow,vhigh));for(auto& event:events)if(selection.contains(event.id.value)){event.start+=dt;mrs::set_midi_event_value(event,mrs::midi_event_value(event)+dv);}graph.repaint();}
    void laneUp(){if(selecting){selecting=false;graph.repaint();return;}if(!dragging)return;dragging=false;try{const auto p=owner.project();if(current(*p)!=baseline)throw std::runtime_error("Clip changed during gesture; cancelled");if(events!=baseline.events){owner.app.set_midi_events(id,events);owner.refresh();}reload();}catch(const std::exception& e){reload();hint.setText(juce::String::fromUTF8(e.what()),juce::dontSendNotification);}}
    void cancel(){if(selecting){selecting=false;selection=initialSelection;}if(dragging){dragging=false;events=baseline.events;}graph.repaint();}
    void timerCallback() override{graph.repaint();if((dragging||selecting)&&(owner.app.recording()||owner.app.engine()->state().playback==mrs::PlaybackState::playing))cancel();if(dragging||selecting)return;try{const auto p=owner.project();if(current(*p)!=clip)reload();}catch(...){cancel();setEnabled(false);}}
};
}
