#include "PianoRoll.h"
#include "MusicalEdit.h"
#include "ControllerEditor.h"
#include <sstream>
#include <cmath>
namespace ui {
class MidiClipPanel final : public juce::Component {
public:
    MidiClipPanel(Desktop& d,mrs::Id clip):owner(d),id(std::move(clip)),roll(d,id),controllerLane(d,id){
        setLookAndFeel(&owner.theme);setName("Piano roll");
        addAndMakeVisible(controllerLane);controllerLane.setComponentID("embedded-controllers");controllerLane.setEmbedded();controllerLane.setVisible(owner.view.controllersOpen);
        viewport.changed=[this]{alignControllers();};roll.viewChanged=[this]{alignControllers();};
        roll.wheel=[this](float delta,juce::ModifierKeys mods,float x,float y){wheel(delta,mods,x,y);};
        addAndMakeVisible(viewport);viewport.setViewedComponent(&roll,false);viewport.setScrollBarsShown(true,true);
        addAndMakeVisible(snap);snap.addItem("Snap off",1);snap.addItem("1/4",2);snap.addItem("1/8",3);snap.addItem("1/16",4);snap.addItem("1/32",5);snap.setSelectedId(4);snap.setTitle("Piano roll snap");snap.onChange=[this]{const std::array<mrs::Tick,5> values{0,mrs::ppq,mrs::ppq/2,mrs::ppq/4,mrs::ppq/8};roll.grid=values[static_cast<std::size_t>(snap.getSelectedId()-1)];roll.repaint();};
        for(auto* b:{&zoomIn,&zoomOut,&copy,&paste,&selectAll,&musical,&controllers,&attach,&details})addAndMakeVisible(b);
        zoomIn.onClick=[this]{zoom(1.25f);};zoomOut.onClick=[this]{zoom(.8f);};copy.onClick=[this]{roll.copy();};paste.onClick=[this]{roll.paste();};selectAll.onClick=[this]{for(const auto& n:roll.notes)roll.selected.insert(n.id.value);roll.repaint();};
        musical.setComponentID("musical-edit-open");musical.onClick=[this]{roll.cancel();auto* musicalPanel=new MusicalEditPanel(owner.theme,[safe=juce::Component::SafePointer<MidiClipPanel>(this)](bool all,const mrs::NoteEdit& edit){if(!safe||!safe->isShowing())throw std::runtime_error("Piano roll is closed");const auto p=safe->owner.project();const auto& clip=*safe->current(*p).midi;std::vector<mrs::Id> selected;for(const auto& n:clip.notes)if(all?(n.start<clip.source_offset+clip.length&&n.start+n.length>clip.source_offset):safe->roll.selected.contains(n.id.value))selected.push_back(n.id);if(selected.empty())throw std::runtime_error("Select notes in piano roll or choose Whole clip");safe->owner.app.edit_midi_notes(safe->id,std::move(selected),edit);safe->owner.refresh();safe->roll.sync();safe->reload();});auto window=std::make_unique<EditorWindow>("Musical note edit",musicalPanel);window->getProperties().set("mrs-midi-clip",true);window->setOwner(owner);owner.windows.push_back(std::move(window));};
        controllers.setComponentID("controller-edit-open");controllers.onClick=[this]{controllerLane.setVisible(!controllerLane.isVisible());if(controllerLane.isVisible())showDetails=false;owner.view.controllersOpen=controllerLane.isVisible();owner.saveSettings();resized();};
        attach.setComponentID("editor-attach");attach.onClick=[this]{deferAttach();};details.onClick=[this]{showDetails=!showDetails;controllerLane.setVisible(!showDetails&&owner.view.controllersOpen);resized();};
        roll.error=[this](auto text){hint.setText(text,juce::dontSendNotification);};roll.changed=[this]{reload();};
        addAndMakeVisible(selector);selector.setTitle("Select MIDI note");selector.onChange=[this]{loadNote();const int index=selector.getSelectedId()-1;if(index>=0&&index<static_cast<int>(notes.size())){roll.selected={notes[static_cast<std::size_t>(index)].id.value};roll.repaint();}};
        const std::array<juce::String,5> names{"Pitch (0..127)","Start (beats)","Length (beats)","Velocity (1..127)","Channel (1..16)"};
        for(std::size_t i=0;i<fields.size();++i){labels[i].setText(names[i],juce::dontSendNotification);labels[i].setFont(owner.theme.font(13));addAndMakeVisible(labels[i]);fields[i].setFont(owner.theme.font(13));fields[i].setTitle(names[i]);fields[i].setComponentID("midi-note-"+juce::String(static_cast<int>(i)));addAndMakeVisible(fields[i]);}
        for(auto* b:{&add,&apply,&remove})addAndMakeVisible(*b);
        add.setComponentID("midi-note-add");apply.setComponentID("midi-note-apply");remove.setComponentID("midi-note-delete");
        add.onClick=[this]{edit(0);};apply.onClick=[this]{edit(1);};remove.onClick=[this]{edit(2);};
        hint.setFont(owner.theme.font(13));hint.setJustificationType(juce::Justification::topLeft);addAndMakeVisible(hint);reload();setSize(1000,800);
    }
    void activate(mrs::Id next){id=next;roll.activate(next);controllerLane.activate(next);showDetails=false;controllerLane.setVisible(owner.view.controllersOpen);reload();resized();}
    ~MidiClipPanel() override{viewport.setViewedComponent(nullptr,false);setLookAndFeel(nullptr);}
    void resized() override{snap.setBounds(16,8,120,26);zoomIn.setBounds(144,8,72,26);zoomOut.setBounds(222,8,72,26);copy.setBounds(302,8,72,26);paste.setBounds(380,8,72,26);selectAll.setBounds(460,8,100,26);musical.setBounds(16,40,130,26);controllers.setBounds(154,40,130,26);details.setBounds(292,40,120,26);attach.setBounds(getWidth()-130,8,114,26);attach.setButtonText(static_cast<bool>(getProperties()["mrs-attached"])?"Detach":"Attach");
        const int formHeight=showDetails?194:0;const int laneHeight=controllerLane.isVisible()?juce::jlimit(290,340,(getHeight()-74-formHeight)/2):0;
        viewport.setBounds(16,74,getWidth()-32,juce::jmax(80,getHeight()-90-formHeight-laneHeight));controllerLane.setBounds(0,viewport.getBottom()+4,getWidth(),laneHeight);
        selector.setVisible(showDetails);for(auto& l:labels)l.setVisible(showDetails);for(auto& f:fields)f.setVisible(showDetails);for(auto* b:{&add,&apply,&remove})b->setVisible(showDetails);hint.setVisible(showDetails);alignControllers();selector.setBounds(16,getHeight()-194,getWidth()-32,26);const int width=(getWidth()-32)/5;for(std::size_t i=0;i<fields.size();++i){const int x=16+static_cast<int>(i)*width;labels[i].setBounds(x,getHeight()-164,width-8,22);fields[i].setBounds(x,getHeight()-140,width-8,26);}add.setBounds(16,getHeight()-108,140,26);apply.setBounds(168,getHeight()-108,140,26);remove.setBounds(320,getHeight()-108,140,26);hint.setBounds(16,getHeight()-76,getWidth()-32,70);if(firstLayout){firstLayout=false;viewport.setViewPosition(static_cast<int>(static_cast<double>(roll.clip.start)/mrs::ppq*roll.beatWidth),PianoRoll::ruler+(127-78)*static_cast<int>(roll.rowHeight));}}
    void paint(juce::Graphics& g) override{g.fillAll(juce::Colour(background));}
private:
    Desktop& owner;mrs::Id id;
    struct RollViewport : juce::Viewport {std::function<void()> changed;void visibleAreaChanged(const juce::Rectangle<int>&) override{if(changed)changed();}};
    PianoRoll roll;ControllerPanel controllerLane;RollViewport viewport;bool showDetails{};juce::ComboBox snap;bool firstLayout{true};
    juce::TextButton zoomIn{"Zoom +"},zoomOut{"Zoom -"},copy{"Copy"},paste{"Paste"},selectAll{"Select all"},musical{"Musical edit..."},controllers{"Controllers"},attach{"Attach"},details{"Note details"};
    void deferAttach(){juce::Component::SafePointer<MidiClipPanel> safe(this);juce::MessageManager::callAsync([safe]{if(safe)safe->owner.attachClipEditor(safe,safe->id,!static_cast<bool>(safe->getProperties()["mrs-attached"]));});}
    void alignControllers(){if(viewport.getWidth()<=0)return;controllerLane.setTimeView(roll.clip.source_offset-roll.clip.start+static_cast<double>(viewport.getViewPositionX())/roll.beatWidth*mrs::ppq,juce::jmax(1,viewport.getWidth()-PianoRoll::keys-16)/roll.beatWidth*mrs::ppq);}
    void wheel(float delta,juce::ModifierKeys mods,float x,float y){roll.cancel();const auto vx=viewport.getViewPositionX(),vy=viewport.getViewPositionY();if(mods.isCtrlDown()){if(mods.isShiftDown()){const float before=roll.beatWidth;roll.beatWidth=juce::jlimit(24.f,384.f,before*std::pow(1.25f,delta*4));roll.sync();viewport.setViewPosition(juce::jmax(0,static_cast<int>((x-PianoRoll::keys)*roll.beatWidth/before-(x-vx-PianoRoll::keys))),vy);}else{const float before=roll.rowHeight;roll.rowHeight=juce::jlimit(8.f,48.f,before+std::round(delta*24));roll.sync();viewport.setViewPosition(vx,juce::jmax(0,static_cast<int>((y-PianoRoll::ruler)*roll.rowHeight/before-(y-vy-PianoRoll::ruler))));}}else if(mods.isShiftDown())viewport.setViewPosition(juce::jmax(0,vx-static_cast<int>(delta*160)),vy);else viewport.setViewPosition(vx,juce::jmax(0,vy-static_cast<int>(delta*128)));alignControllers();}
    void zoom(float factor){const auto x=viewport.getViewPositionX();roll.cancel();roll.beatWidth=juce::jlimit(24.f,384.f,roll.beatWidth*factor);roll.sync();viewport.setViewPosition(static_cast<int>(x*factor),viewport.getViewPositionY());alignControllers();}
    juce::ComboBox selector;
    std::array<juce::Label,5> labels;std::array<juce::TextEditor,5> fields;
    juce::TextButton add{"Add note"},apply{"Apply note"},remove{"Delete note"};juce::Label hint;
    std::vector<mrs::MidiNote> notes;
    const mrs::Clip& current(const mrs::Project& p) const{auto i=std::find_if(p.clips.begin(),p.clips.end(),[&](const auto& c){return c.id==id;});if(i==p.clips.end()||!i->midi)throw std::runtime_error("MIDI clip no longer exists");return *i;}
    double number(std::size_t i) const{std::istringstream in(fields[i].getText().toStdString());in.imbue(std::locale::classic());double value{};if(!(in>>value)||!std::isfinite(value))throw std::runtime_error("Enter a valid number in every field");in>>std::ws;if(!in.eof())throw std::runtime_error("Unexpected characters in note field");return value;}
    void loadNote(){const int index=selector.getSelectedId()-1;mrs::MidiNote n;if(index>=0&&index<static_cast<int>(notes.size()))n=notes[static_cast<std::size_t>(index)];else{const auto p=owner.project();n.start=current(*p).midi->source_offset;}
        fields[0].setText(juce::String(n.pitch));fields[1].setText(juce::String(static_cast<double>(n.start)/mrs::ppq,6));fields[2].setText(juce::String(static_cast<double>(n.length)/mrs::ppq,6));fields[3].setText(juce::String(n.velocity));fields[4].setText(juce::String(n.channel+1));apply.setEnabled(index>=0);remove.setEnabled(index>=0);}
    void reload(int selected=1){const auto p=owner.project();const auto& c=current(*p);notes=c.midi->notes;selector.clear(juce::dontSendNotification);for(std::size_t i=0;i<notes.size();++i){const auto& n=notes[i];selector.addItem("Note "+juce::String(static_cast<int>(i)+1)+" | pitch "+juce::String(n.pitch)+" | beat "+juce::String(static_cast<double>(n.start)/mrs::ppq,3),static_cast<int>(i)+1);}selector.setTextWhenNothingSelected("Empty MIDI clip — add a note");selector.setSelectedId(juce::jlimit(0,static_cast<int>(notes.size()),selected),juce::dontSendNotification);loadNote();
        hint.setText("Start and length use quarter-note beats. Start is relative to the original clip source;\nDouble click: create/remove. Ctrl/Shift click or drag empty space: select. Drag: move; right edge: length.\nAlt-drag: velocity. Ctrl+C/V/A/Z/Y: copy/paste/select/Undo/Redo. Delete: remove.",juce::dontSendNotification);}
    void edit(int operation){try{const auto p=owner.project();auto next=current(*p).midi->notes;const int index=selector.getSelectedId()-1;
        if(operation!=0&&(index<0||index>=static_cast<int>(notes.size())))throw std::runtime_error("Select a note");
        auto at=next.end();if(operation!=0){at=std::find_if(next.begin(),next.end(),[&](const auto& n){return n.id==notes[static_cast<std::size_t>(index)].id;});if(at==next.end())throw std::runtime_error("Note changed; reopen this editor");}
        int selected=index+1;
        if(operation==2){next.erase(at);}else{mrs::MidiNote n;n.id=operation==0?mrs::new_id():at->id;const auto pitch=number(0),start=number(1),length=number(2),velocity=number(3),channel=number(4);
            if(pitch<0||pitch>127||std::floor(pitch)!=pitch||velocity<1||velocity>127||std::floor(velocity)!=velocity||channel<1||channel>16||std::floor(channel)!=channel||start<0||start>static_cast<double>(mrs::max_tick)/mrs::ppq||length<=0||length>static_cast<double>(mrs::max_tick)/mrs::ppq)throw std::runtime_error("Note values are outside their allowed ranges");
            n.pitch=static_cast<int>(pitch);n.velocity=static_cast<int>(velocity);n.channel=static_cast<int>(channel)-1;n.start=static_cast<mrs::Tick>(std::llround(start*mrs::ppq));n.length=static_cast<mrs::Tick>(std::llround(length*mrs::ppq));if(operation==0){next.push_back(n);selected=static_cast<int>(next.size());}else *at=n;
        }
        owner.app.set_midi_notes(id,std::move(next));owner.refresh();roll.sync();reload(selected);
    }catch(const std::exception& e){hint.setText(juce::String::fromUTF8(e.what()),juce::dontSendNotification);}}
};

class AudioClipPanel final : public juce::Component, private juce::Timer {
public:
    AudioClipPanel(Desktop& d,mrs::Id clip):owner(d),id(std::move(clip)),wave(*this){setLookAndFeel(&owner.theme);setName("Audio editor");setComponentID("audio-clip-editor");for(auto* c:std::array<juce::Component*,6>{&wave,&attach,&start,&end,&apply,&hint})addAndMakeVisible(c);start.setTitle("Clip start (seconds)");start.setComponentID("audio-trim-start");end.setComponentID("audio-trim-end");end.setTitle("Clip end (seconds)");apply.setTitle("Apply audio trim");attach.setComponentID("editor-attach");apply.setComponentID("audio-trim-apply");attach.onClick=[this]{juce::Component::SafePointer<AudioClipPanel> safe(this);juce::MessageManager::callAsync([safe]{if(safe)safe->owner.attachClipEditor(safe,safe->id,!static_cast<bool>(safe->getProperties()["mrs-attached"]));});};apply.onClick=[this]{owner.run([&]{const auto p=owner.project();const auto parse=[](const juce::TextEditor& f){std::istringstream in(f.getText().toStdString());in.imbue(std::locale::classic());double n{};if(!(in>>n)||!std::isfinite(n)||n<0||n>static_cast<double>(mrs::max_sample)/192000)throw std::runtime_error("Enter valid trim seconds");in>>std::ws;if(!in.eof())throw std::runtime_error("Unexpected trim characters");return n;};owner.app.trim_clip(id,static_cast<mrs::Sample>(std::llround(parse(start)*p->sample_rate)),static_cast<mrs::Sample>(std::llround(parse(end)*p->sample_rate)));reload();});};setSize(1000,600);reload();startTimer(150);}
    ~AudioClipPanel() override{setLookAndFeel(nullptr);}
    void resized() override{attach.setBounds(getWidth()-130,8,114,26);attach.setButtonText(static_cast<bool>(getProperties()["mrs-attached"])?"Detach":"Attach");wave.setBounds(16,44,getWidth()-32,getHeight()-132);start.setBounds(16,getHeight()-76,150,26);end.setBounds(174,getHeight()-76,150,26);apply.setBounds(332,getHeight()-76,160,26);hint.setBounds(16,getHeight()-40,getWidth()-32,28);}
    void paint(juce::Graphics& g) override{g.fillAll(juce::Colour(background));g.setColour(juce::Colours::white);g.drawText("Audio editor - "+juce::String::fromUTF8(clip.name.c_str()),16,8,getWidth()-160,26,juce::Justification::left);}
private:
    struct Wave final:juce::Component {AudioClipPanel& owner;explicit Wave(AudioClipPanel& p):owner(p){}void paint(juce::Graphics& g) override{g.fillAll(juce::Colour(surface));if(const auto* waveform=owner.owner.app.waveform(owner.clip.source)){const int channels=static_cast<int>(waveform->channels());for(int ch=0;ch<channels;++ch){const float height=static_cast<float>(getHeight())/channels,centre=(ch+.5f)*height;g.setColour(juce::Colours::skyblue);for(int x=0;x<getWidth();++x){const auto begin=owner.clip.source_offset+owner.clip.length*x/juce::jmax(1,getWidth()),rangeEnd=owner.clip.source_offset+owner.clip.length*(x+1)/juce::jmax(1,getWidth());const auto peak=waveform->range(begin,std::max(begin+1,rangeEnd),static_cast<unsigned>(ch));g.drawVerticalLine(x,centre-peak.maximum*height*.45f,centre-peak.minimum*height*.45f);}}}else{g.setColour(juce::Colours::lightgrey);g.drawText("Waveform unavailable",getLocalBounds(),juce::Justification::centred);}}};
    Desktop& owner;mrs::Id id;mrs::Clip clip;Wave wave;juce::TextButton attach{"Attach"},apply{"Apply trim"};juce::TextEditor start,end;juce::Label hint;
    void reload(){const auto p=owner.project();const auto it=std::find_if(p->clips.begin(),p->clips.end(),[&](const auto& c){return c.id==id;});if(it==p->clips.end()||it->midi){setEnabled(false);return;}clip=*it;start.setText(juce::String(static_cast<double>(clip.start)/p->sample_rate,6));end.setText(juce::String(static_cast<double>(clip.start+clip.length)/p->sample_rate,6));hint.setText("Start / end in project seconds. Apply trim: one Undo. Ctrl+Z/Y in main window.",juce::dontSendNotification);wave.repaint();}
    void timerCallback() override{const auto p=owner.project();const auto it=std::find_if(p->clips.begin(),p->clips.end(),[&](const auto& c){return c.id==id;});if(it==p->clips.end()){setEnabled(false);return;}if(it->start!=clip.start||it->length!=clip.length||it->source_offset!=clip.source_offset)reload();wave.repaint();}
};
void Desktop::openMidiClip(mrs::Id id){openClipEditor(std::move(id));}
bool Desktop::clipEditorOpen() const{if(dockedEditor&&dockedClip&&dockedEditor->isVisible())return true;for(const auto& w:windows)if(w->isVisible()&&static_cast<bool>(w->getProperties()["mrs-midi-id"].isString())&&!w->getProperties()["mrs-midi-id"].toString().isEmpty())return true;return false;}
void Desktop::activateClip(mrs::Id id){selectedClip=id;selectedClips={id.value};const bool opened=clipEditorOpen();if(opened)openClipEditor(id);refresh();}
void Desktop::toggleEditor(){if(clipEditorOpen()){if(dockedEditor)dockedEditor->setVisible(false);for(auto& w:windows)if(!w->getProperties()["mrs-midi-id"].toString().isEmpty())w->setVisible(false);setWorkspace(mrs::desktop::Workspace::arrange);}else openSelectedEditor();}
void Desktop::openClipEditor(mrs::Id id){
    const auto p=project();const auto clip=std::find_if(p->clips.begin(),p->clips.end(),[&](const auto& c){return c.id==id;});if(clip==p->clips.end())throw std::runtime_error("Select an audio or MIDI clip");selectedClip=id;selectedTrack=clip->track;
    const auto create=[&]()->juce::Component*{return clip->midi?static_cast<juce::Component*>(new MidiClipPanel(*this,id)):static_cast<juce::Component*>(new AudioClipPanel(*this,id));};
    if(view.editorAttached){if(auto* midiPanel=dynamic_cast<MidiClipPanel*>(dockedEditor.get());midiPanel&&clip->midi)midiPanel->activate(id);else if(dockedClip!=id||!dockedEditor)dockedEditor.reset(create());dockedClip=id;dockedEditor->getProperties().set("mrs-attached",true);addAndMakeVisible(dockedEditor.get());setWorkspace(mrs::desktop::Workspace::edit);return;}
    for(auto& w:windows)if(w->isVisible()&&!w->getProperties()["mrs-midi-id"].toString().isEmpty()){if(auto* midiPanel=dynamic_cast<MidiClipPanel*>(w->getContentComponent());midiPanel&&clip->midi)midiPanel->activate(id);else w->setContentOwned(create(),true);w->getProperties().set("mrs-midi-id",juce::String::fromUTF8(id.value.c_str()));w->setName(clip->midi?"Piano roll":"Audio editor");w->toFront(true);setWorkspace(mrs::desktop::Workspace::edit);return;}
    auto window=std::make_unique<EditorWindow>(clip->midi?"Piano roll":"Audio editor",create());window->setResizable(true,false);window->setResizeLimits(720,550,1800,1400);window->getProperties().set("mrs-midi-clip",true);window->getProperties().set("mrs-midi-id",juce::String::fromUTF8(id.value.c_str()));window->setOwner(*this);window->onClose=[this]{setWorkspace(mrs::desktop::Workspace::arrange);};windows.push_back(std::move(window));setWorkspace(mrs::desktop::Workspace::edit);
}
void Desktop::openSelectedEditor(){const auto p=project();if(!selectedClip){const auto head=app.engine()->state().sample;const mrs::Timeline time(p->time,p->sample_rate);for(const auto& c:p->clips)if((!selectedTrack||c.track==*selectedTrack)&&mrs::clip_start(c,time)<=head&&mrs::clip_end(c,time)>head){selectedClip=c.id;break;}}if(!selectedClip)throw std::runtime_error("Select an audio or MIDI clip, then press Edit");setWorkspace(mrs::desktop::Workspace::edit);openClipEditor(*selectedClip);}
void Desktop::attachClipEditor(juce::Component* content,mrs::Id id,bool attach){
    view.editorAttached=attach;saveSettings();
    if(attach){for(auto& w:windows)if(w->getContentComponent()==content){w->setContentNonOwned(content,false);w->clearContentComponent();w->setVisible(false);dockedEditor.reset(content);dockedClip=id;content->getProperties().set("mrs-attached",true);addAndMakeVisible(content);setWorkspace(mrs::desktop::Workspace::edit);return;}}
    else if(dockedEditor.get()==content){auto* editorContent=dockedEditor.release();dockedClip.reset();removeChildComponent(editorContent);editorContent->getProperties().set("mrs-attached",false);editorContent->setSize(1000,800);auto window=std::make_unique<EditorWindow>(editorContent->getName(),editorContent);window->setResizable(true,false);window->setResizeLimits(720,550,1800,1400);window->getProperties().set("mrs-midi-clip",true);window->getProperties().set("mrs-midi-id",juce::String::fromUTF8(id.value.c_str()));window->setOwner(*this);window->onClose=[this]{setWorkspace(mrs::desktop::Workspace::arrange);};windows.push_back(std::move(window));setWorkspace(mrs::desktop::Workspace::edit);}
}
}
