if(NOT WIN32)
  message(FATAL_ERROR "The JUCE shell is validated on Windows only")
endif()
if(CMAKE_VERSION VERSION_LESS 3.22)
  message(FATAL_ERROR "JUCE requires CMake 3.22 or newer")
endif()
set(MRS_JUCE_SDK_ROOT "" CACHE PATH "Local official JUCE 9.0.3 source directory")
if(NOT EXISTS "${MRS_JUCE_SDK_ROOT}/CMakeLists.txt")
  message(FATAL_ERROR "Set MRS_JUCE_SDK_ROOT to local JUCE 9.0.3. Configure never downloads it.")
endif()
file(READ "${MRS_JUCE_SDK_ROOT}/CMakeLists.txt" juce_source)
if(NOT juce_source MATCHES "project\\(JUCE VERSION 9\\.0\\.3")
  message(FATAL_ERROR "The JUCE shell requires pinned JUCE 9.0.3")
endif()
add_subdirectory("${MRS_JUCE_SDK_ROOT}" "${CMAKE_BINARY_DIR}/juce-sdk" EXCLUDE_FROM_ALL)
file(GLOB transport_icons CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/assets/ui/icons/transport/*.svg")
juce_add_binary_data(mrs_juce_assets SOURCES "${PROJECT_SOURCE_DIR}/apps/studio-juce/assets/NotoSans.ttf" ${transport_icons})
juce_add_gui_app(MoonRiverStudioJuce VERSION 0.1.0 PRODUCT_NAME "Moon River Studio JUCE")
add_library(mrs_diagnostics STATIC apps/diagnostics/src/session.cpp)
target_include_directories(mrs_diagnostics PUBLIC apps/diagnostics/include)
target_compile_features(mrs_diagnostics PUBLIC cxx_std_20)
add_executable(mrs_crash_reporter apps/diagnostics/src/reporter.cpp)
target_compile_features(mrs_crash_reporter PRIVATE cxx_std_20)
target_link_libraries(mrs_crash_reporter PRIVATE dbghelp)
add_executable(mrs_dump_inspect tools/dump_inspect.cpp)
target_compile_features(mrs_dump_inspect PRIVATE cxx_std_20)
target_compile_options(mrs_dump_inspect PRIVATE /W4 /WX /utf-8)
target_link_libraries(mrs_dump_inspect PRIVATE dbghelp)
target_sources(MoonRiverStudioJuce PRIVATE apps/studio-juce/src/Main.cpp apps/studio-juce/src/Desktop.cpp apps/studio-juce/src/Editors.cpp apps/studio-juce/src/MidiEditor.cpp apps/studio-juce/src/MidiRecordSmoke.cpp apps/studio-juce/src/Smoke.cpp apps/studio-juce/src/Profiling.cpp)
target_link_libraries(MoonRiverStudioJuce PRIVATE mrs_desktop mrs_juce_assets mrs_diagnostics juce::juce_gui_basics)
target_compile_definitions(MoonRiverStudioJuce PRIVATE JUCE_WEB_BROWSER=0 JUCE_USE_CURL=0)
if(NOT MRS_BUILD_VST3)
  message(FATAL_ERROR "JUCE J2 requires MRS_BUILD_VST3=ON and the cached VST3 SDK")
endif()
add_dependencies(MoonRiverStudioJuce mrs_vst3_scan mrs_crash_reporter)
add_custom_command(TARGET MoonRiverStudioJuce POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:mrs_vst3_scan>" "$<TARGET_FILE_DIR:MoonRiverStudioJuce>/mrs_vst3_scan.exe")
add_custom_command(TARGET MoonRiverStudioJuce POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:mrs_crash_reporter>" "$<TARGET_FILE_DIR:MoonRiverStudioJuce>/mrs_crash_reporter.exe")
if(MRS_BUILD_ASIO)
  target_link_libraries(MoonRiverStudioJuce PRIVATE mrs_asio)
  target_compile_definitions(MoonRiverStudioJuce PRIVATE MRS_HAS_ASIO=1)
endif()
# JUCE's amalgamated third-party sources have their own warnings policy.
# Compile our translation unit with /WX; do not impose it on the framework.
if(MSVC)
  target_compile_options(mrs_diagnostics PRIVATE /W4 /WX /utf-8 /Zi)
  target_compile_options(mrs_crash_reporter PRIVATE /W4 /WX /utf-8 /Zi)
  # Matching optimized-release symbols are necessary to analyze crash stacks.
  foreach(t MoonRiverStudioJuce mrs_core mrs_audio mrs_processing mrs_desktop mrs_vst3)
    target_compile_options(${t} PRIVATE /Zi)
  endforeach()
  target_link_options(MoonRiverStudioJuce PRIVATE /DEBUG:FULL /INCREMENTAL:NO /OPT:REF /OPT:ICF)
  target_link_options(mrs_crash_reporter PRIVATE /DEBUG:FULL /INCREMENTAL:NO)
  target_compile_options(MoonRiverStudioJuce PRIVATE /WX-)
  set_source_files_properties(apps/studio-juce/src/Main.cpp apps/studio-juce/src/Desktop.cpp apps/studio-juce/src/Editors.cpp apps/studio-juce/src/MidiEditor.cpp apps/studio-juce/src/MidiRecordSmoke.cpp apps/studio-juce/src/Smoke.cpp apps/studio-juce/src/Profiling.cpp PROPERTIES COMPILE_OPTIONS "/WX")
endif()
if(BUILD_TESTING)
  add_executable(mrs_diagnostics_probe tests/diagnostics_probe.cpp)
  target_link_libraries(mrs_diagnostics_probe PRIVATE mrs_diagnostics)
  add_executable(mrs_diagnostics_tests tests/diagnostics_tests.cpp)
  target_link_libraries(mrs_diagnostics_tests PRIVATE mrs_diagnostics dbghelp)
  target_compile_options(mrs_diagnostics_probe PRIVATE /W4 /WX /utf-8 /Zi)
  target_compile_options(mrs_diagnostics_tests PRIVATE /W4 /WX /utf-8)
  target_link_options(mrs_diagnostics_probe PRIVATE /DEBUG:FULL /INCREMENTAL:NO)
  add_test(NAME crash_diagnostics COMMAND mrs_diagnostics_tests "$<TARGET_FILE:mrs_diagnostics_probe>" "$<TARGET_FILE:mrs_crash_reporter>")
  set_tests_properties(crash_diagnostics PROPERTIES TIMEOUT 60 RUN_SERIAL TRUE)
  add_test(NAME juce_diagnostics_smoke COMMAND MoonRiverStudioJuce --j3-smoke --diagnostics-smoke --fixture "$<TARGET_FILE:mrs_vst3_fixture>")
  set_tests_properties(juce_diagnostics_smoke PROPERTIES TIMEOUT 45 RUN_SERIAL TRUE)
  add_test(NAME juce_j1_smoke COMMAND MoonRiverStudioJuce --j1-smoke)
  set_tests_properties(juce_j1_smoke PROPERTIES TIMEOUT 30)
  add_dependencies(MoonRiverStudioJuce mrs_vst3_fixture)
  add_test(NAME juce_j2_smoke COMMAND MoonRiverStudioJuce --smoke-test --fixture "$<TARGET_FILE:mrs_vst3_fixture>")
  set_tests_properties(juce_j2_smoke PROPERTIES TIMEOUT 45)
  add_test(NAME juce_j3_smoke COMMAND MoonRiverStudioJuce --j3-smoke --fixture "$<TARGET_FILE:mrs_vst3_fixture>")
  set_tests_properties(juce_j3_smoke PROPERTIES TIMEOUT 45)
  set_tests_properties(juce_j2_smoke juce_j3_smoke PROPERTIES RUN_SERIAL TRUE)
endif()
