if(NOT WIN32)
  message(FATAL_ERROR "The JUCE shell is validated on Windows only")
endif()
if(CMAKE_VERSION VERSION_LESS 3.22)
  message(FATAL_ERROR "JUCE requires CMake 3.22 or newer")
endif()
set(MRS_JUCE_SDK_ROOT "" CACHE PATH "Local official JUCE 9.0.3 source directory")
if(NOT EXISTS "${MRS_JUCE_SDK_ROOT}/CMakeLists.txt")
  message(FATAL_ERROR "Set MRS_JUCE_SDK_ROOT to local JUCE 9.0.3. Configure never downloads it.")
endif()
file(READ "${MRS_JUCE_SDK_ROOT}/CMakeLists.txt" juce_source)
if(NOT juce_source MATCHES "project\\(JUCE VERSION 9\\.0\\.3")
  message(FATAL_ERROR "The JUCE shell requires pinned JUCE 9.0.3")
endif()
add_subdirectory("${MRS_JUCE_SDK_ROOT}" "${CMAKE_BINARY_DIR}/juce-sdk" EXCLUDE_FROM_ALL)
juce_add_binary_data(mrs_juce_assets SOURCES "${PROJECT_SOURCE_DIR}/apps/studio-juce/assets/NotoSans.ttf")
juce_add_gui_app(MoonRiverStudioJuce VERSION 0.1.0 PRODUCT_NAME "Moon River Studio JUCE")
target_sources(MoonRiverStudioJuce PRIVATE apps/studio-juce/src/Main.cpp apps/studio-juce/src/Desktop.cpp apps/studio-juce/src/Editors.cpp apps/studio-juce/src/Smoke.cpp apps/studio-juce/src/Profiling.cpp)
target_link_libraries(MoonRiverStudioJuce PRIVATE mrs_desktop mrs_juce_assets juce::juce_gui_basics)
target_compile_definitions(MoonRiverStudioJuce PRIVATE JUCE_WEB_BROWSER=0 JUCE_USE_CURL=0)
if(NOT MRS_BUILD_VST3)
  message(FATAL_ERROR "JUCE J2 requires MRS_BUILD_VST3=ON and the cached VST3 SDK")
endif()
add_dependencies(MoonRiverStudioJuce mrs_vst3_scan)
add_custom_command(TARGET MoonRiverStudioJuce POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:mrs_vst3_scan>" "$<TARGET_FILE_DIR:MoonRiverStudioJuce>/mrs_vst3_scan.exe")
if(MRS_BUILD_ASIO)
  target_link_libraries(MoonRiverStudioJuce PRIVATE mrs_asio)
  target_compile_definitions(MoonRiverStudioJuce PRIVATE MRS_HAS_ASIO=1)
endif()
# JUCE's amalgamated third-party sources have their own warnings policy.
# Compile our translation unit with /WX; do not impose it on the framework.
if(MSVC)
  target_compile_options(MoonRiverStudioJuce PRIVATE /WX-)
  set_source_files_properties(apps/studio-juce/src/Main.cpp apps/studio-juce/src/Desktop.cpp apps/studio-juce/src/Editors.cpp apps/studio-juce/src/Smoke.cpp apps/studio-juce/src/Profiling.cpp PROPERTIES COMPILE_OPTIONS "/WX")
endif()
if(BUILD_TESTING)
  add_test(NAME juce_j1_smoke COMMAND MoonRiverStudioJuce --j1-smoke)
  set_tests_properties(juce_j1_smoke PROPERTIES TIMEOUT 30)
  add_dependencies(MoonRiverStudioJuce mrs_vst3_fixture)
  add_test(NAME juce_j2_smoke COMMAND MoonRiverStudioJuce --smoke-test --fixture "$<TARGET_FILE:mrs_vst3_fixture>")
  set_tests_properties(juce_j2_smoke PROPERTIES TIMEOUT 45)
  add_test(NAME juce_j3_smoke COMMAND MoonRiverStudioJuce --j3-smoke --fixture "$<TARGET_FILE:mrs_vst3_fixture>")
  set_tests_properties(juce_j3_smoke PROPERTIES TIMEOUT 45)
  set_tests_properties(juce_j2_smoke juce_j3_smoke PROPERTIES RUN_SERIAL TRUE)
endif()
