include(FetchContent)
set(MRS_PORTAUDIO_REVISION "873e3c83fbe2f57ebcf59083e627a3f8fa051ffe")
set(PA_BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(PA_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(PA_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(PA_USE_ASIO ON CACHE BOOL "" FORCE)
foreach(api PA_USE_DS PA_USE_WMME PA_USE_WASAPI PA_USE_WDMKS PA_USE_WDMKS_DEVICE_INFO PA_USE_JACK)
  set(${api} OFF CACHE BOOL "" FORCE)
endforeach()
# SDK stays in the build directory; never vendor/commit/redistribute the SDK.
# Optional path allows an already obtained developer SDK archive to be used.
set(MRS_ASIO_SDK_ZIP "" CACHE FILEPATH "Optional official ASIO SDK zip")
if(MRS_ASIO_SDK_ZIP)
  set(ASIO_SDK_ZIP_PATH "${MRS_ASIO_SDK_ZIP}" CACHE FILEPATH "" FORCE)
endif()
FetchContent_Declare(portaudio
  URL "https://github.com/PortAudio/portaudio/archive/${MRS_PORTAUDIO_REVISION}.tar.gz")
FetchContent_MakeAvailable(portaudio)
if(NOT TARGET ASIO::host)
  message(FATAL_ERROR "ASIO SDK was not found; an ASIO-less build must not masquerade as vendor ASIO")
endif()
if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/_deps/portaudio-build/asiosdk.zip")
  file(SHA256 "${CMAKE_CURRENT_BINARY_DIR}/_deps/portaudio-build/asiosdk.zip" sdk_sha)
  message(STATUS "ASIO SDK archive SHA256: ${sdk_sha}")
endif()
