include(FetchContent)
if(POLICY CMP0135)
  cmake_policy(SET CMP0135 NEW)
endif()
set(MRS_PORTAUDIO_REVISION "873e3c83fbe2f57ebcf59083e627a3f8fa051ffe")
set(MRS_ASIO_SDK_SHA256 "d5ebf0c20dd2c5f43771fd0c1418f4b361bf52434ee670097cfa6b3a335e2eca"
    CACHE STRING "Checksum of the official SDK archive used for this developer build")
set(MRS_ASIO_SDK_ZIP "" CACHE FILEPATH "Optional official ASIO SDK zip")
if(NOT MRS_ASIO_SDK_ZIP)
  set(MRS_ASIO_SDK_ZIP "${CMAKE_CURRENT_BINARY_DIR}/mrs-asiosdk.zip")
  file(DOWNLOAD "https://www.steinberg.net/asiosdk" "${MRS_ASIO_SDK_ZIP}"
       EXPECTED_HASH "SHA256=${MRS_ASIO_SDK_SHA256}" TLS_VERIFY ON
       STATUS sdk_status SHOW_PROGRESS)
  list(GET sdk_status 0 sdk_error)
  if(NOT sdk_error EQUAL 0)
    message(FATAL_ERROR "Official ASIO SDK download failed: ${sdk_status}")
  endif()
endif()
file(SHA256 "${MRS_ASIO_SDK_ZIP}" sdk_sha)
if(NOT sdk_sha STREQUAL MRS_ASIO_SDK_SHA256)
  message(FATAL_ERROR "SDK archive checksum mismatch; review version/license before explicitly updating the pin")
endif()
message(STATUS "ASIO SDK archive SHA256: ${sdk_sha}")
set(ASIO_SDK_ZIP_PATH "${MRS_ASIO_SDK_ZIP}" CACHE FILEPATH "" FORCE)
set(PA_BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(PA_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(PA_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(PA_USE_ASIO ON CACHE BOOL "" FORCE)
foreach(api PA_USE_DS PA_USE_WMME PA_USE_WASAPI PA_USE_WDMKS PA_USE_WDMKS_DEVICE_INFO PA_USE_JACK)
  set(${api} OFF CACHE BOOL "" FORCE)
endforeach()
FetchContent_Declare(portaudio
  URL "https://github.com/PortAudio/portaudio/archive/${MRS_PORTAUDIO_REVISION}.tar.gz")
FetchContent_MakeAvailable(portaudio)
get_target_property(mrs_pa_definitions portaudio INTERFACE_COMPILE_DEFINITIONS)
if(NOT "PA_USE_ASIO=1" IN_LIST mrs_pa_definitions)
  message(FATAL_ERROR "PortAudio ASIO host was not enabled; refusing an ASIO-less hardware build")
endif()
