option(MRS_BUILD_VST3 "Build Windows x64 VST3 effect hosting" OFF)
set(MRS_VST3_SDK_ROOT "" CACHE PATH "Locally cached Steinberg SDK with base/pluginterfaces/public.sdk/cmake")
if(MRS_BUILD_VST3)
  if(NOT WIN32 OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "VST3 hosting requires Windows x64")
  endif()
  if(NOT EXISTS "${MRS_VST3_SDK_ROOT}/public.sdk/source/vst/hosting/module.h")
    message(FATAL_ERROR "Set MRS_VST3_SDK_ROOT to a populated local VST3 SDK; configure never downloads it")
  endif()
  set(SMTG_ENABLE_VST3_PLUGIN_EXAMPLES OFF CACHE BOOL "" FORCE)
  set(SMTG_ENABLE_VST3_HOSTING_EXAMPLES OFF CACHE BOOL "" FORCE)
  set(SMTG_ENABLE_VSTGUI_SUPPORT OFF CACHE BOOL "" FORCE)
  set(SMTG_USE_STATIC_CRT ON CACHE BOOL "" FORCE)
  set(SMTG_CREATE_PLUGIN_LINK OFF CACHE BOOL "" FORCE)
  add_subdirectory("${MRS_VST3_SDK_ROOT}" "${CMAKE_BINARY_DIR}/vst3sdk" EXCLUDE_FROM_ALL)
  foreach(sdk_target base pluginterfaces sdk_common sdk_hosting sdk)
    set_property(TARGET ${sdk_target} PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  endforeach()
  add_library(mrs_vst3 STATIC core/processing/src/vst3.cpp core/processing/src/vst3_scan.cpp
    "${MRS_VST3_SDK_ROOT}/public.sdk/source/vst/hosting/module_win32.cpp"
    "${MRS_VST3_SDK_ROOT}/public.sdk/source/common/memorystream.cpp"
    "${MRS_VST3_SDK_ROOT}/public.sdk/source/vst/hosting/plugprovider.cpp")
  target_include_directories(mrs_vst3 SYSTEM PRIVATE "${MRS_VST3_SDK_ROOT}")
  target_include_directories(mrs_vst3 PRIVATE core/include core/audio/include)
  target_compile_features(mrs_vst3 PRIVATE cxx_std_20)
  target_compile_options(mrs_vst3 PRIVATE /W3 /WX- /utf-8)
  set_source_files_properties("${MRS_VST3_SDK_ROOT}/public.sdk/source/vst/hosting/module_win32.cpp"
    PROPERTIES COMPILE_OPTIONS "/Zc:char8_t-")
  target_link_libraries(mrs_vst3 PRIVATE sdk_hosting ole32 shell32 user32)
  target_link_libraries(mrs_processing PUBLIC mrs_vst3)
  target_compile_definitions(mrs_processing PUBLIC MRS_HAS_VST3=1)
  add_executable(mrs_vst3_scan tools/vst3_scan.cpp)
  target_link_libraries(mrs_vst3_scan PRIVATE mrs_processing)
  if(BUILD_TESTING)
    add_library(mrs_vst3_fixture MODULE tests/vst3_fixture.cpp "${MRS_VST3_SDK_ROOT}/public.sdk/source/main/dllmain.cpp"
      "${MRS_VST3_SDK_ROOT}/public.sdk/source/vst/vstsinglecomponenteffect.cpp")
    target_include_directories(mrs_vst3_fixture SYSTEM PRIVATE "${MRS_VST3_SDK_ROOT}")
    target_link_libraries(mrs_vst3_fixture PRIVATE sdk user32)
    target_compile_features(mrs_vst3_fixture PRIVATE cxx_std_20)
    set_target_properties(mrs_vst3_fixture PROPERTIES PREFIX "" SUFFIX ".vst3")
    add_executable(mrs_vst3_tests tests/vst3_tests.cpp)
    target_link_libraries(mrs_vst3_tests PRIVATE mrs_desktop)
    foreach(suite probe processing state editor scan desktop realtime)
      add_test(NAME vst3_${suite} COMMAND mrs_vst3_tests ${suite} $<TARGET_FILE:mrs_vst3_fixture> $<TARGET_FILE:mrs_vst3_scan>)
    endforeach()
  endif()
endif()
